use super::*;

// ── App module codegen (auto-wired router) ──────────────────

/// Render the API `mod` tree file (`generated_api_mods.rs`).
///
/// Uses `#[path]` attributes pointing to the source directory so that
/// `include!()` from `OUT_DIR` resolves module files correctly.
pub fn render_generated_api_mods(
    api_entries: &[GeneratedApiRoute],
    src_root: &Path,
    has_middleware: bool,
) -> String {
    let mut out = String::new();
    out.push_str("// @generated by pilcrow-routekit. Do not edit manually.\n");

    // Expose src/middleware.rs as `crate::middleware` so the generated shim can call it.
    if has_middleware {
        let middleware_path = src_root.join("middleware.rs");
        let middleware_path_str = middleware_path.to_string_lossy().replace('\\', "/");
        let _ = writeln!(out, "#[path = \"{middleware_path_str}\"]");
        out.push_str("pub mod middleware;\n");
    }

    // Expose src/params/ as `crate::params` when the directory exists.
    let params_dir = src_root.join("params");
    if params_dir.exists() {
        if let Ok(read_dir) = fs::read_dir(&params_dir) {
            let params_dir_str = params_dir.to_string_lossy().replace('\\', "/");
            let mut param_mods: Vec<String> = read_dir
                .flatten()
                .filter_map(|entry| {
                    let path = entry.path();
                    if path.extension().and_then(|e| e.to_str()) == Some("rs") {
                        path.file_stem()
                            .and_then(|s| s.to_str())
                            .map(|s| s.to_string())
                    } else {
                        None
                    }
                })
                .collect();
            param_mods.sort();
            if !param_mods.is_empty() {
                let _ = writeln!(out, "#[path = \"{params_dir_str}\"]");
                out.push_str("pub mod params {\n");
                for mod_name in &param_mods {
                    let _ = writeln!(out, "    pub mod {mod_name};");
                }
                out.push_str("}\n");
            }
        }
    }

    if api_entries.is_empty() {
        return out;
    }

    // Use #[path] to resolve mod files relative to the actual source tree
    let api_dir = src_root.join("api");
    let api_dir_str = api_dir.to_string_lossy().replace('\\', "/");
    let _ = writeln!(out, "#[path = \"{api_dir_str}\"]");
    out.push_str("pub mod api {\n");

    // Emit leaf modules only (strip the `api::` prefix)
    for entry in api_entries {
        let leaf = entry
            .module_path
            .strip_prefix("api::")
            .unwrap_or(&entry.module_path);
        // For nested modules like "users::id", we need nested mod declarations.
        // For simplicity, only handle single-level for now; nested will use #[path] too.
        if !leaf.contains("::") {
            let _ = writeln!(out, "    pub mod {leaf};");
        }
    }

    // Handle nested API modules
    let nested: Vec<_> = api_entries
        .iter()
        .filter_map(|e| {
            e.module_path
                .strip_prefix("api::")
                .filter(|l| l.contains("::"))
        })
        .collect();

    if !nested.is_empty() {
        // Build sub-tree for nested entries
        #[derive(Default)]
        struct SubNode {
            children: std::collections::BTreeMap<String, SubNode>,
            is_leaf: bool,
        }

        fn sub_insert(node: &mut SubNode, segments: &[&str]) {
            if segments.is_empty() {
                return;
            }
            let child = node.children.entry(segments[0].to_string()).or_default();
            if segments.len() == 1 {
                child.is_leaf = true;
            } else {
                sub_insert(child, &segments[1..]);
            }
        }

        fn sub_emit(node: &SubNode, indent: usize, base_path: &str) -> String {
            let mut out = String::new();
            let pad = "    ".repeat(indent);
            for (name, child) in &node.children {
                let child_path = format!("{base_path}/{name}");
                if child.is_leaf && child.children.is_empty() {
                    let _ = writeln!(out, "{pad}pub mod {name};");
                } else {
                    let _ = writeln!(out, "{pad}#[path = \"{child_path}\"]");
                    let _ = writeln!(out, "{pad}pub mod {name} {{");
                    out.push_str(&sub_emit(child, indent + 1, &child_path));
                    let _ = writeln!(out, "{pad}}}");
                }
            }
            out
        }

        let mut root = SubNode::default();
        for path in &nested {
            let segments: Vec<&str> = path.split("::").collect();
            sub_insert(&mut root, &segments);
        }
        out.push_str(&sub_emit(&root, 1, &api_dir_str));
    }

    out.push_str("}\n");
    out
}

/// Render the full app module that auto-wires all page and API routes.
///
/// This generates `generated_app.rs` containing:
/// - An include of `generated_templates.rs`
/// - A `build_router()` function returning a fully-wired `axum::Router`
///
/// API routes reference modules via `crate::` paths since the mod tree
/// is included separately at crate root level.
///
/// `error_module_for_page` maps each page symbol to its nearest `_error.html` module name.
/// `not_found_module` is the module name of `_not_found.html` (registered as axum fallback).
pub fn render_generated_app_module(
    page_entries: &[GeneratedPageRoute],
    api_entries: &[GeneratedApiRoute],
    load_map: &HashMap<String, Option<LoadSignature>>,
    layout_fields_map: &HashMap<String, LayoutFieldsInfo>,
    error_module_for_page: &HashMap<String, String>,
    not_found_module: Option<&str>,
    loading_module_for_page: &HashMap<String, String>,
    action_map: &HashMap<String, Vec<ActionFn>>,
    page_options_map: &HashMap<String, PageOptions>,
    deferred_fields_map: &HashMap<String, Vec<String>>,
    deferred_html_fields_map: &HashMap<String, Vec<String>>,
    has_middleware: bool,
) -> String {
    let mut out = String::new();
    out.push_str("// @generated by pilcrow-routekit. Do not edit manually.\n\n");

    // Include generated templates
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("mod __pilcrow_gen {\n");
    out.push_str("    include!(concat!(env!(\"OUT_DIR\"), \"/generated_templates.rs\"));\n");
    out.push_str("}\n\n");

    // build_router function
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub fn build_router() -> ::pilcrow_web::axum::Router {\n");
    out.push_str("    ::pilcrow_web::axum::Router::new()\n");

    // Page routes
    for entry in page_entries {
        let page_load = load_map.get(&entry.symbol).copied().flatten();
        let chain_info = layout_fields_map.get(&entry.symbol);
        let error_mod = error_module_for_page.get(&entry.symbol).map(String::as_str);
        let loading_mod = loading_module_for_page
            .get(&entry.symbol)
            .map(String::as_str);
        let page_actions: Option<&Vec<ActionFn>> = action_map.get(&entry.symbol);

        let pattern = rust_string(&entry.pattern);
        let mod_name = &entry.symbol;
        let render_fn = &entry.render_symbol;
        let deferred_fields: &[String] = deferred_fields_map
            .get(&entry.symbol)
            .map(Vec::as_slice)
            .unwrap_or(&[]);
        let deferred_html_fields: &[String] = deferred_html_fields_map
            .get(&entry.symbol)
            .map(Vec::as_slice)
            .unwrap_or(&[]);

        // Collect the active chain: (var_index, layout_mod, field_names, sig) for each layout
        // in the chain that has a load() function.
        let active_chain: Vec<(usize, &str, &Vec<String>, LoadSignature)> = chain_info
            .map(|info| {
                info.chain
                    .iter()
                    .enumerate()
                    .filter_map(|(i, (lmod, fields))| {
                        load_map
                            .get(lmod.as_str())
                            .copied()
                            .flatten()
                            .map(|sig| (i, lmod.as_str(), fields, sig))
                    })
                    .collect()
            })
            .unwrap_or_default();

        let any_layout_load = !active_chain.is_empty();
        let any_layout_client = active_chain.iter().any(|(_, _, _, sig)| sig.wants_client);
        let page_wants_client = page_load.map_or(false, |s| s.wants_client);
        let needs_client = any_layout_client || page_wants_client;

        let any_layout_req = active_chain.iter().any(|(_, _, _, sig)| sig.wants_req);
        let page_wants_req = page_load.map_or(false, |s| s.wants_req);
        let has_param_matchers = !entry.param_matchers.is_empty();
        let needs_req = any_layout_req || page_wants_req || has_param_matchers;

        // PilcrowClient is FromRequestParts and must come before Req (FromRequest).
        let closure_args = match (needs_req, needs_client) {
            (true, true) => "client: ::pilcrow_web::PilcrowClient, req: ::pilcrow_web::Req",
            (true, false) => "req: ::pilcrow_web::Req",
            (false, true) => "client: ::pilcrow_web::PilcrowClient",
            (false, false) => "",
        };

        let pattern_str = entry.pattern.as_str();
        let _ = writeln!(
            out,
            "        .route({pattern}, ::pilcrow_web::axum::routing::get(|{closure_args}| {{"
        );
        let _ = writeln!(
            out,
            "            use ::pilcrow_web::tracing::Instrument as _;"
        );
        let _ = writeln!(
            out,
            "            let __req_span = ::pilcrow_web::tracing::info_span!(\"GET\", http.route = {});",
            rust_string(pattern_str)
        );
        out.push_str("            async move {\n");

        // ── Param matcher guards ────────────────────────────────────────────────
        if has_param_matchers {
            out.push_str("            use ::pilcrow_web::axum::response::IntoResponse;\n");
            let mut sorted_matchers: Vec<(&String, &String)> =
                entry.param_matchers.iter().collect();
            sorted_matchers.sort_by_key(|(k, _)| k.as_str());
            for (param_name, matcher_mod) in &sorted_matchers {
                let _ = writeln!(
                    out,
                    "            if !crate::params::{matcher_mod}::match_param(req.params.get(\"{param_name}\").map(|s| s.as_str()).unwrap_or(\"\")) {{"
                );
                out.push_str("                return (::pilcrow_web::StatusCode::NOT_FOUND, \"not found\").into_response();\n");
                out.push_str("            }\n");
            }
        }

        if !any_layout_load && page_load.is_none() {
            // ── Case 1: static page ─────────────────────────────────────────────
            let _ = writeln!(
                out,
                "            let props = __pilcrow_gen::{mod_name}::Props::default();"
            );
            let _ = writeln!(
                out,
                "            let html = __pilcrow_gen::{mod_name}::{render_fn}(props).expect(\"template render failed\");"
            );
            out.push_str(&emit_loading_append(loading_mod));
            out.push_str("            ::pilcrow_web::axum::response::Html(html)\n");
        } else {
            out.push_str("            use ::pilcrow_web::axum::response::IntoResponse;\n");
            // Clone the response handle before req consumption so load() calls
            // can write to it and we can apply it after rendering.
            if needs_req {
                out.push_str("            let __resp_handle = req.res.clone();\n");
            }

            // ── Layout loads (one per active chain entry, outermost first) ───────
            // When a client is cloned: it must be cloned for every call except the
            // very last consumer (page or last layout).
            let _last_client_consumer_is_page = page_wants_client;
            let layout_client_consumers = active_chain
                .iter()
                .filter(|(_, _, _, s)| s.wants_client)
                .count();
            let mut client_clones_left = if needs_client {
                let total = layout_client_consumers + if page_wants_client { 1 } else { 0 };
                total.saturating_sub(1)
            } else {
                0
            };

            let layout_req_consumers = active_chain
                .iter()
                .filter(|(_, _, _, s)| s.wants_req)
                .count();
            let mut req_clones_left = if needs_req {
                let total = layout_req_consumers + if page_wants_req { 1 } else { 0 };
                total.saturating_sub(1)
            } else {
                0
            };

            for (idx, layout_mod, _, lsig) in &active_chain {
                let req_arg = if lsig.wants_req {
                    if req_clones_left > 0 {
                        req_clones_left -= 1;
                        "req.clone()"
                    } else {
                        "req"
                    }
                } else {
                    ""
                };
                let client_arg = if lsig.wants_client {
                    if client_clones_left > 0 {
                        client_clones_left -= 1;
                        "client.clone()"
                    } else {
                        "client"
                    }
                } else {
                    ""
                };
                let layout_call_args = match (req_arg, client_arg) {
                    ("", "") => String::new(),
                    (r, "") => r.to_string(),
                    ("", cl) => cl.to_string(),
                    (r, cl) => format!("{r}, {cl}"),
                };
                let call_expr = format!("__pilcrow_gen::{layout_mod}::load({layout_call_args})");
                let awaited = if lsig.is_async {
                    format!("{call_expr}.await")
                } else {
                    call_expr
                };
                let var = format!("layout_data_{idx}");
                if lsig.returns_result {
                    let _ = writeln!(out, "            let {var} = match {awaited} {{");
                    out.push_str("                Ok(p) => p,\n");
                    out.push_str(&emit_error_branch(error_mod));
                    out.push_str("            };\n");
                } else {
                    let _ = writeln!(out, "            let {var} = {awaited};");
                }
            }

            // ── Page load ────────────────────────────────────────────────────────
            if let Some(psig) = page_load {
                let req_arg = if psig.wants_req {
                    if req_clones_left > 0 {
                        req_clones_left -= 1;
                        "req.clone()"
                    } else {
                        "req"
                    }
                } else {
                    ""
                };
                let client_arg = if psig.wants_client {
                    if client_clones_left > 0 {
                        client_clones_left -= 1;
                        "client.clone()"
                    } else {
                        "client"
                    }
                } else {
                    ""
                };
                let page_call_args = match (req_arg, client_arg) {
                    ("", "") => String::new(),
                    (r, "") => r.to_string(),
                    ("", cl) => cl.to_string(),
                    (r, cl) => format!("{r}, {cl}"),
                };
                let call_expr = format!("__pilcrow_gen::{mod_name}::load({page_call_args})");
                let awaited = if psig.is_async {
                    format!("{call_expr}.await")
                } else {
                    call_expr
                };
                if psig.returns_result {
                    let _ = writeln!(out, "            let page_data = match {awaited} {{");
                    out.push_str("                Ok(p) => p,\n");
                    out.push_str(&emit_error_branch(error_mod));
                    out.push_str("            };\n");
                } else {
                    let _ = writeln!(out, "            let page_data = {awaited};");
                }
            }

            // ── Construct props ──────────────────────────────────────────────────
            if any_layout_load {
                // Layout chain contributed fields → use __MergedProps.
                let info = chain_info.expect("chain_info present when active_chain is non-empty");
                let _ = writeln!(
                    out,
                    "            let props = __pilcrow_gen::{mod_name}::__MergedProps {{"
                );
                // Layout fields: each entry maps to its var (layout_data_{i}).
                for (idx, _, field_names, _) in &active_chain {
                    let var = format!("layout_data_{idx}");
                    for field in *field_names {
                        let _ = writeln!(out, "                {field}: {var}.{field},");
                    }
                }
                // Page fields: from page_data if page has load(), else Default.
                if page_load.is_some() {
                    for field in &info.page_field_names {
                        let _ = writeln!(out, "                {field}: page_data.{field},");
                    }
                } else {
                    for field in &info.page_field_names {
                        let _ = writeln!(out, "                {field}: Default::default(),");
                    }
                }
                out.push_str("            };\n");
            } else {
                // Only page has load() → Props directly.
                let _ = writeln!(out, "            let props = page_data;");
            }

            let has_any_deferred = !deferred_fields.is_empty() || !deferred_html_fields.is_empty();
            if has_any_deferred && !any_layout_load {
                // ── Deferred streaming response ───────────────────────────────────
                // Step 1: extract futures and loading HTML from DeferredHtml fields.
                for field in deferred_html_fields {
                    let _ = writeln!(
                        out,
                        "            let (__deferred_html_{field}_fut, __deferred_html_{field}_loading) = page_data.{field}.__into_parts();"
                    );
                }
                // Step 2: extract Deferred<T> futures.
                for field in deferred_fields {
                    let _ = writeln!(
                        out,
                        "            let __deferred_{field} = page_data.{field};"
                    );
                }
                // Step 3: build shell props — replace deferred fields with placeholders.
                let _ = writeln!(
                    out,
                    "            let __shell_props = __pilcrow_gen::{mod_name}::Props {{"
                );
                for field in deferred_fields {
                    let _ = writeln!(
                        out,
                        "                {field}: ::pilcrow_web::Deferred::ready(Default::default()),"
                    );
                }
                for field in deferred_html_fields {
                    let _ = writeln!(
                        out,
                        "                {field}: ::pilcrow_web::DeferredHtml::__slot({name}, __deferred_html_{field}_loading.clone()),",
                        name = rust_string(field)
                    );
                }
                out.push_str("                ..page_data\n");
                out.push_str("            };\n");
                // Step 4: render shell.
                let _ = writeln!(
                    out,
                    "            let __shell_html = __pilcrow_gen::{mod_name}::{render_fn}(__shell_props).expect(\"template render failed\");"
                );
                // Step 5: replace text markers from DeferredHtml Display with real slot spans.
                for field in deferred_html_fields {
                    let marker = rust_string(&format!("__pilcrow_html_slot_{field}__"));
                    let _ = writeln!(
                        out,
                        "            let mut __slot_span_{field} = String::new();"
                    );
                    let _ = writeln!(
                        out,
                        "            __slot_span_{field}.push_str(\"<span data-pilcrow-slot=\\\"{field}\\\">\");"
                    );
                    let _ = writeln!(
                        out,
                        "            __slot_span_{field}.push_str(&__deferred_html_{field}_loading);"
                    );
                    let _ = writeln!(
                        out,
                        "            __slot_span_{field}.push_str(\"</span>\");"
                    );
                    let _ = writeln!(
                        out,
                        "            let __shell_html = __shell_html.replace({marker}, &__slot_span_{field});"
                    );
                }
                out.push_str(&emit_loading_append(loading_mod));
                // Step 6: build patch streams.
                out.push_str("            let __json_patches = ::pilcrow_web::__deferred_patch_stream(vec![\n");
                for field in deferred_fields {
                    let field_lit = rust_string(field);
                    let _ = writeln!(
                        out,
                        "                ({field_lit}, Box::pin(async move {{ ::pilcrow_web::__serialize_deferred(__deferred_{field}.resolve().await) }})),"
                    );
                }
                out.push_str("            ]);\n");
                out.push_str("            let __html_patches = ::pilcrow_web::__deferred_html_patch_stream(vec![\n");
                for field in deferred_html_fields {
                    let field_lit = rust_string(field);
                    let _ = writeln!(
                        out,
                        "                ({field_lit}, Box::pin(async move {{ __deferred_html_{field}_fut.await }})),"
                    );
                }
                out.push_str("            ]);\n");
                // Step 7: inject shim(s) before </head>.
                let json_shim = if !deferred_fields.is_empty() {
                    "window.__pilcrow_deferred=function(f,v){var d={};d[f]=v;Silcrow.patch(d,document.body)}"
                } else {
                    ""
                };
                let html_shim = if !deferred_html_fields.is_empty() {
                    "window.__pd=function(s,h){var e=document.querySelector('[data-pilcrow-slot=\"'+s+'\"]');if(e){var t=document.createElement('template');t.innerHTML=h;e.replaceWith(t.content.cloneNode(true))}}"
                } else {
                    ""
                };
                let shim_body = match (json_shim, html_shim) {
                    ("", h) => h.to_string(),
                    (j, "") => j.to_string(),
                    (j, h) => format!("{j};{h}"),
                };
                let shim_tag = format!("<script>{shim_body}</script>");
                let shim_lit = rust_string(&shim_tag);
                let _ = writeln!(out, "            const __DEFERRED_SHIM: &str = {shim_lit};");
                out.push_str("            let __shell_html = if let Some(__pos) = __shell_html.find(\"</head>\") {\n");
                out.push_str("                let mut __s = String::with_capacity(__shell_html.len() + __DEFERRED_SHIM.len());\n");
                out.push_str("                __s.push_str(&__shell_html[..__pos]);\n");
                out.push_str("                __s.push_str(__DEFERRED_SHIM);\n");
                out.push_str("                __s.push_str(&__shell_html[__pos..]);\n");
                out.push_str("                __s\n");
                out.push_str("            } else {\n");
                out.push_str("                format!(\"{}{}\", __DEFERRED_SHIM, __shell_html)\n");
                out.push_str("            };\n");
                out.push_str("            return ::pilcrow_web::deferred_response_combined(__shell_html, __json_patches, __html_patches);\n");
            } else {
                let _ = writeln!(
                    out,
                    "            let html = __pilcrow_gen::{mod_name}::{render_fn}(props).expect(\"template render failed\");"
                );
                out.push_str(&emit_loading_append(loading_mod));
                if needs_req {
                    out.push_str("            let mut __response = ::pilcrow_web::axum::response::Html(html).into_response();\n");
                    out.push_str("            __resp_handle.apply_to(&mut __response);\n");
                    out.push_str("            __response\n");
                } else {
                    out.push_str(
                        "            ::pilcrow_web::axum::response::Html(html).into_response()\n",
                    );
                }
            }
        }

        out.push_str("            }.instrument(__req_span)\n        }))\n");

        // ── Action POST route (same URL, dispatched by `?/<name>`) ──────────────
        if let Some(actions) = page_actions {
            if !actions.is_empty() {
                out.push_str(&emit_action_route(
                    actions,
                    &entry.pattern,
                    mod_name,
                    error_mod,
                ));
            }
        }

        // ── Trailing slash redirect routes ───────────────────────────────────────
        if let Some(opts) = page_options_map.get(&entry.symbol) {
            let base = &entry.pattern;
            match opts.trailing_slash {
                TrailingSlash::Always if !base.ends_with('/') && base != "/" => {
                    let slashed = rust_string(&format!("{base}/"));
                    let bare = rust_string(base.as_str());
                    let _ = writeln!(
                        out,
                        "        .route({bare}, ::pilcrow_web::axum::routing::get(|| async move {{"
                    );
                    let _ = writeln!(
                        out,
                        "            ::pilcrow_web::axum::response::Redirect::permanent({slashed})"
                    );
                    out.push_str("        }))\n");
                }
                TrailingSlash::Ignore if !base.ends_with('/') && base != "/" => {
                    let slashed = rust_string(&format!("{base}/"));
                    let bare = rust_string(base.as_str());
                    let _ = writeln!(
                        out,
                        "        .route({slashed}, ::pilcrow_web::axum::routing::get(|| async move {{"
                    );
                    let _ = writeln!(
                        out,
                        "            ::pilcrow_web::axum::response::Redirect::permanent({bare})"
                    );
                    out.push_str("        }))\n");
                }
                _ => {}
            }
        }
    }

    // API routes — reference via crate:: since mod tree is at crate root
    for entry in api_entries {
        let pattern = rust_string(&entry.pattern);
        let mod_path = &entry.module_path;
        let _ = writeln!(out, "        .nest({pattern}, crate::{mod_path}::router())");
    }

    // Not-found fallback — registered last so it matches any unhandled request.
    if let Some(nf_mod) = not_found_module {
        let render_fn = format!("render_{nf_mod}");
        out.push_str("        .fallback(|| async {\n");
        let _ = writeln!(
            out,
            "            let props = __pilcrow_gen::{nf_mod}::Props {{}};"
        );
        let _ = writeln!(
            out,
            "            let html = __pilcrow_gen::{nf_mod}::{render_fn}(props)"
        );
        out.push_str(
            "                .unwrap_or_else(|_| \"<h1>404 Not Found</h1>\".to_string());\n",
        );
        out.push_str("            (\n");
        out.push_str("                ::pilcrow_web::StatusCode::NOT_FOUND,\n");
        out.push_str("                ::pilcrow_web::axum::response::Html(html)\n");
        out.push_str("            )\n");
        out.push_str("        })\n");
    }

    // Apply the user's src/middleware.rs as an axum layer if it exists.
    if has_middleware {
        out.push_str(
            "        .layer(::pilcrow_web::axum::middleware::from_fn(__pilcrow_middleware))\n",
        );
    }

    // CSRF protection is always-on and outermost: state-changing form submissions
    // with a cross-origin `Origin` (or `Referer`) are rejected before user middleware
    // or route handlers see them. Safe methods and non-form content types pass through.
    out.push_str("        .layer(::pilcrow_web::axum::middleware::from_fn(::pilcrow_web::__csrf_middleware))\n");

    out.push_str("}\n");

    // Generated middleware shim: extracts Req from parts (body stays intact),
    // calls the user's `middleware()`, then forwards to the next handler.
    if has_middleware {
        out.push('\n');
        out.push_str("async fn __pilcrow_middleware(\n");
        out.push_str("    req: ::pilcrow_web::axum::extract::Request,\n");
        out.push_str("    next: ::pilcrow_web::axum::middleware::Next,\n");
        out.push_str(") -> ::pilcrow_web::axum::response::Response {\n");
        out.push_str("    let (mut parts, body) = req.into_parts();\n");
        out.push_str("    let pilcrow_req = ::pilcrow_web::Req::__from_middleware_parts(&mut parts, &()).await;\n");
        out.push_str(
            "    let forwarded = ::pilcrow_web::axum::extract::Request::from_parts(parts, body);\n",
        );
        out.push_str("    let pilcrow_next = ::pilcrow_web::Next::new(next, forwarded);\n");
        out.push_str("    crate::middleware::middleware(pilcrow_req, pilcrow_next).await\n");
        out.push_str("}\n");
    }

    out
}

/// Generate and write the app module and API mods files.
pub fn write_generated_app_module(
    page_entries: &[GeneratedPageRoute],
    api_entries: &[GeneratedApiRoute],
    load_map: &HashMap<String, Option<LoadSignature>>,
    layout_fields_map: &HashMap<String, LayoutFieldsInfo>,
    error_module_for_page: &HashMap<String, String>,
    not_found_module: Option<&str>,
    loading_module_for_page: &HashMap<String, String>,
    action_map: &HashMap<String, Vec<ActionFn>>,
    page_options_map: &HashMap<String, PageOptions>,
    deferred_fields_map: &HashMap<String, Vec<String>>,
    deferred_html_fields_map: &HashMap<String, Vec<String>>,
    has_middleware: bool,
    src_root: &Path,
    out_dir: impl AsRef<Path>,
) -> io::Result<()> {
    let out_dir = out_dir.as_ref();
    fs::create_dir_all(out_dir)?;

    let app_source = render_generated_app_module(
        page_entries,
        api_entries,
        load_map,
        layout_fields_map,
        error_module_for_page,
        not_found_module,
        loading_module_for_page,
        action_map,
        page_options_map,
        deferred_fields_map,
        deferred_html_fields_map,
        has_middleware,
    );
    fs::write(out_dir.join("generated_app.rs"), app_source)?;

    let mods_source = render_generated_api_mods(api_entries, src_root, has_middleware);
    fs::write(out_dir.join("generated_api_mods.rs"), mods_source)?;

    Ok(())
}
