import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  ListToolsRequestSchema,
  CallToolRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";

import { execSync } from "child_process";
import { readdirSync, readFileSync, statSync, existsSync } from "fs";
import { join, relative, resolve, basename } from "path";

// ── Config ───────────────────────────────────────────────────

const PROJECT_ROOT = resolve(
  process.env.PILCROW_ROOT || findProjectRoot() || process.cwd()
);

const DEFAULT_MANIFEST = join(
  PROJECT_ROOT,
  "sandbox/apps/web/Cargo.toml"
);

function findProjectRoot() {
  // Walk up from this file looking for a workspace Cargo.toml
  let dir = resolve(new URL(".", import.meta.url).pathname);
  for (let i = 0; i < 10; i++) {
    if (existsSync(join(dir, "Cargo.toml")) && existsSync(join(dir, "crates"))) {
      return dir;
    }
    const parent = resolve(dir, "..");
    if (parent === dir) break;
    dir = parent;
  }
  return null;
}

// ── OUT_DIR Discovery ────────────────────────────────────────

function findOutDir(manifestPath) {
  const manifest = resolve(manifestPath || DEFAULT_MANIFEST);
  if (!existsSync(manifest)) {
    throw new Error(`Manifest not found: ${manifest}`);
  }

  // The crate name from the manifest directory
  const manifestDir = resolve(manifest, "..");
  const targetDir = findTargetDir(manifestDir);

  // Look in target/debug/build/<pkg>-<hash>/out/ for generated_app.rs
  const buildDir = join(targetDir, "debug", "build");
  if (!existsSync(buildDir)) {
    throw new Error(
      `Build directory not found: ${buildDir}\nRun codegen_build first.`
    );
  }

  const candidates = [];
  for (const entry of readdirSync(buildDir)) {
    const outDir = join(buildDir, entry, "out");
    const marker = join(outDir, "generated_app.rs");
    if (existsSync(marker)) {
      const stat = statSync(marker);
      candidates.push({ path: outDir, mtime: stat.mtimeMs });
    }
  }

  if (candidates.length === 0) {
    throw new Error(
      "No generated_app.rs found in any build output directory.\n" +
        "Run codegen_build first."
    );
  }

  // Pick the most recently modified one
  candidates.sort((a, b) => b.mtime - a.mtime);
  return candidates[0].path;
}

function findTargetDir(manifestDir) {
  // Check for a .cargo/config.toml that overrides target-dir, otherwise
  // walk up to find the workspace root's target/
  let dir = manifestDir;
  for (let i = 0; i < 10; i++) {
    const cargoConfig = join(dir, ".cargo", "config.toml");
    if (existsSync(cargoConfig)) {
      const text = readFileSync(cargoConfig, "utf8");
      const match = text.match(/target-dir\s*=\s*"([^"]+)"/);
      if (match) return resolve(dir, match[1]);
    }
    // If this dir has a workspace Cargo.toml, use its target/
    if (existsSync(join(dir, "Cargo.toml"))) {
      const toml = readFileSync(join(dir, "Cargo.toml"), "utf8");
      if (toml.includes("[workspace]")) {
        return join(dir, "target");
      }
    }
    const parent = resolve(dir, "..");
    if (parent === dir) break;
    dir = parent;
  }
  // Fallback: target/ relative to the manifest
  return join(manifestDir, "target");
}

// ── File tree helper ─────────────────────────────────────────

function listFilesRecursive(dir, base) {
  const results = [];
  base = base || dir;
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const rel = relative(base, full);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      results.push(...listFilesRecursive(full, base));
    } else {
      results.push({ path: rel, size: stat.size, mtime: stat.mtime.toISOString() });
    }
  }
  return results;
}

// ── Tool Definitions ─────────────────────────────────────────

const TOOLS = [
  {
    definition: {
      name: "codegen_build",
      description:
        "Build a Pilcrow web app, triggering the routekit build.rs codegen pipeline. " +
        "Returns build output including any errors. Defaults to the sandbox app.",
      inputSchema: {
        type: "object",
        properties: {
          manifest: {
            type: "string",
            description:
              "Path to Cargo.toml (absolute or relative to project root). " +
              "Defaults to sandbox/apps/web/Cargo.toml.",
          },
        },
      },
    },
    handler: handleBuild,
  },
  {
    definition: {
      name: "codegen_list",
      description:
        "List all files generated by the routekit build pipeline in $OUT_DIR. " +
        "Shows generated_app.rs, generated_routes.rs, transpiled templates, etc.",
      inputSchema: {
        type: "object",
        properties: {
          manifest: {
            type: "string",
            description: "Path to Cargo.toml. Defaults to sandbox app.",
          },
        },
      },
    },
    handler: handleList,
  },
  {
    definition: {
      name: "codegen_read",
      description:
        "Read a generated file from $OUT_DIR. Use codegen_list to see available files. " +
        "Common files: generated_app.rs, generated_routes.rs, generated_api_mods.rs, " +
        "and transpiled templates under pilcrow_templates/.",
      inputSchema: {
        type: "object",
        properties: {
          file: {
            type: "string",
            description:
              'Relative path within $OUT_DIR, e.g. "generated_app.rs" or ' +
              '"pilcrow_templates/pages/index.html".',
          },
          manifest: {
            type: "string",
            description: "Path to Cargo.toml. Defaults to sandbox app.",
          },
          head: {
            type: "number",
            description: "Return only the first N lines.",
          },
          tail: {
            type: "number",
            description: "Return only the last N lines.",
          },
        },
        required: ["file"],
      },
    },
    handler: handleRead,
  },
];

// ── Tool Handlers ────────────────────────────────────────────

function handleBuild({ manifest }) {
  const manifestPath = manifest
    ? resolve(PROJECT_ROOT, manifest)
    : DEFAULT_MANIFEST;

  if (!existsSync(manifestPath)) {
    return { content: [{ type: "text", text: `Manifest not found: ${manifestPath}` }], isError: true };
  }

  try {
    const output = execSync(
      `cargo build --manifest-path "${manifestPath}" 2>&1`,
      {
        cwd: PROJECT_ROOT,
        timeout: 120_000,
        maxBuffer: 10 * 1024 * 1024,
        encoding: "utf8",
      }
    );

    // Find OUT_DIR after successful build
    let outDirInfo = "";
    try {
      const outDir = findOutDir(manifestPath);
      const files = listFilesRecursive(outDir);
      outDirInfo =
        `\n\nOUT_DIR: ${outDir}\n` +
        `Generated files (${files.length}):\n` +
        files.map((f) => `  ${f.path} (${f.size} bytes)`).join("\n");
    } catch (_) {
      // Non-fatal — the build succeeded but we couldn't find OUT_DIR
    }

    return {
      content: [
        {
          type: "text",
          text: `Build succeeded.\n\n${output.trim()}${outDirInfo}`,
        },
      ],
    };
  } catch (err) {
    return {
      content: [
        {
          type: "text",
          text: `Build failed.\n\n${err.stdout || ""}${err.stderr || err.message}`,
        },
      ],
      isError: true,
    };
  }
}

function handleList({ manifest }) {
  try {
    const outDir = findOutDir(manifest);
    const files = listFilesRecursive(outDir);
    const tree = files
      .map((f) => `${f.path}  (${f.size} bytes, ${f.mtime})`)
      .join("\n");

    return {
      content: [
        {
          type: "text",
          text: `OUT_DIR: ${outDir}\n\n${tree || "(empty)"}`,
        },
      ],
    };
  } catch (err) {
    return {
      content: [{ type: "text", text: err.message }],
      isError: true,
    };
  }
}

function handleRead({ file, manifest, head, tail }) {
  try {
    const outDir = findOutDir(manifest);
    const filePath = join(outDir, file);

    // Prevent path traversal
    if (!filePath.startsWith(outDir)) {
      return {
        content: [{ type: "text", text: "Path traversal not allowed." }],
        isError: true,
      };
    }

    if (!existsSync(filePath)) {
      // Suggest similar files
      const allFiles = listFilesRecursive(outDir);
      const needle = basename(file).toLowerCase();
      const suggestions = allFiles
        .filter((f) => f.path.toLowerCase().includes(needle))
        .map((f) => f.path)
        .slice(0, 5);

      let msg = `File not found: ${file}`;
      if (suggestions.length > 0) {
        msg += `\n\nDid you mean:\n${suggestions.map((s) => `  ${s}`).join("\n")}`;
      }
      return { content: [{ type: "text", text: msg }], isError: true };
    }

    let text = readFileSync(filePath, "utf8");

    if (head != null) {
      text = text.split("\n").slice(0, head).join("\n");
    } else if (tail != null) {
      const lines = text.split("\n");
      text = lines.slice(Math.max(0, lines.length - tail)).join("\n");
    }

    // Add line numbers
    const numbered = text
      .split("\n")
      .map((line, i) => {
        const lineNum = (head != null ? i + 1 : tail != null ? text.split("\n").length - text.split("\n").length + i + 1 : i + 1);
        return `${String(lineNum).padStart(4)}  ${line}`;
      })
      .join("\n");

    return {
      content: [
        {
          type: "text",
          text: `${file} (${outDir})\n${"─".repeat(60)}\n${numbered}`,
        },
      ],
    };
  } catch (err) {
    return {
      content: [{ type: "text", text: err.message }],
      isError: true,
    };
  }
}

// ── Server Setup ─────────────────────────────────────────────

const TOOL_MAP = new Map(TOOLS.map((t) => [t.definition.name, t]));

async function main() {
  const server = new Server(
    { name: "pilcrow-codegen-inspector", version: "0.1.0" },
    { capabilities: { tools: {} } }
  );

  server.setRequestHandler(ListToolsRequestSchema, () => ({
    tools: TOOLS.map((t) => t.definition),
  }));

  server.setRequestHandler(CallToolRequestSchema, (request) => {
    const { name, arguments: args } = request.params;
    const tool = TOOL_MAP.get(name);
    if (!tool) {
      return {
        content: [{ type: "text", text: `Unknown tool: ${name}` }],
        isError: true,
      };
    }
    return tool.handler(args || {});
  });

  const transport = new StdioServerTransport();
  await server.connect(transport);
  process.stderr.write(
    `[codegen-inspector] Ready — project root: ${PROJECT_ROOT}\n`
  );
}

main().catch((err) => {
  process.stderr.write(`[codegen-inspector] Fatal: ${err.message}\n`);
  process.exit(1);
});
