use std::fmt::Write as _;
use std::fs;
use std::io;
use std::path::Path;

use crate::discovery::build_page_routes;

/// One generated page route entry for build-time manifests.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedPageRoute {
    pub pattern: String,
    pub template_path: String,
    pub symbol: String,
}

/// Build a page-route manifest from `src/pages/**/*.html`.
pub fn build_generated_page_manifest(
    src_root: impl AsRef<Path>,
) -> io::Result<Vec<GeneratedPageRoute>> {
    let src_root = src_root.as_ref();
    let pages_dir = src_root.join("pages");
    let pages_dir_norm = normalize_path_text(&pages_dir);

    let routes = build_page_routes(src_root)?;
    let mut generated = routes
        .into_iter()
        .map(|route| {
            let symbol = build_symbol_name(&route.template_path, &pages_dir_norm);
            GeneratedPageRoute {
                pattern: route.pattern,
                template_path: route.template_path,
                symbol,
            }
        })
        .collect::<Vec<_>>();

    generated.sort_by(|a, b| {
        a.pattern
            .cmp(&b.pattern)
            .then_with(|| a.template_path.cmp(&b.template_path))
    });

    Ok(generated)
}

/// Render a Rust module source for discovered page routes.
///
/// The generated module contains:
/// - `GeneratedPageRoute` (borrowed static fields)
/// - `GENERATED_PAGE_ROUTES` const slice
/// - `generated_routes()` accessor
/// - `register_generated_routes(...)` helper for framework glue
pub fn render_generated_routes_module(entries: &[GeneratedPageRoute]) -> String {
    let mut out = String::new();

    out.push_str("// @generated by pilcrow-routekit. Do not edit manually.\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct GeneratedPageRoute {\n");
    out.push_str("    pub pattern: &'static str,\n");
    out.push_str("    pub template_path: &'static str,\n");
    out.push_str("    pub symbol: &'static str,\n");
    out.push_str("}\n\n");
    out.push_str("pub const GENERATED_PAGE_ROUTES: &[GeneratedPageRoute] = &[\n");

    for entry in entries {
        let pattern = rust_string(&entry.pattern);
        let template_path = rust_string(&entry.template_path);
        let symbol = rust_string(&entry.symbol);
        let _ = writeln!(
            out,
            "    GeneratedPageRoute {{ pattern: {pattern}, template_path: {template_path}, symbol: {symbol} }},"
        );
    }

    out.push_str("];\n\n");
    out.push_str("pub fn generated_routes() -> &'static [GeneratedPageRoute] {\n");
    out.push_str("    GENERATED_PAGE_ROUTES\n");
    out.push_str("}\n\n");
    out.push_str("pub fn register_generated_routes<R, F>(mut router: R, mut register: F) -> R\n");
    out.push_str("where\n");
    out.push_str("    F: FnMut(R, &'static GeneratedPageRoute) -> R,\n");
    out.push_str("{\n");
    out.push_str("    for route in GENERATED_PAGE_ROUTES {\n");
    out.push_str("        router = register(router, route);\n");
    out.push_str("    }\n");
    out.push_str("    router\n");
    out.push_str("}\n");
    out.push_str("\n");
    out.push_str("pub fn pilcrow_router<R, F>(router: R, register: F) -> R\n");
    out.push_str("where\n");
    out.push_str("    F: FnMut(R, &'static GeneratedPageRoute) -> R,\n");
    out.push_str("{\n");
    out.push_str("    register_generated_routes(router, register)\n");
    out.push_str("}\n");

    out
}

/// Generate and write the routes module to the given `out_file` path.
pub fn write_generated_routes_module(
    src_root: impl AsRef<Path>,
    out_file: impl AsRef<Path>,
) -> io::Result<Vec<GeneratedPageRoute>> {
    let entries = build_generated_page_manifest(src_root)?;
    let source = render_generated_routes_module(&entries);

    let out_file = out_file.as_ref();
    if let Some(parent) = out_file.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(out_file, source)?;

    Ok(entries)
}

fn build_symbol_name(template_path: &str, pages_dir_norm: &str) -> String {
    let path = normalize_path_text(Path::new(template_path));
    let relative = path
        .strip_prefix(pages_dir_norm)
        .unwrap_or(&path)
        .trim_start_matches('/');
    let without_ext = relative.strip_suffix(".html").unwrap_or(relative);

    let mut symbol = String::new();
    let mut prev_underscore = false;
    for ch in without_ext.chars() {
        let mapped = if ch.is_ascii_alphanumeric() {
            ch.to_ascii_lowercase()
        } else {
            '_'
        };

        if mapped == '_' {
            if !prev_underscore {
                symbol.push('_');
            }
            prev_underscore = true;
        } else {
            symbol.push(mapped);
            prev_underscore = false;
        }
    }

    let symbol = symbol.trim_matches('_');
    let symbol = if symbol.is_empty() { "index" } else { symbol };
    format!("page_{symbol}")
}

fn normalize_path_text(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

fn rust_string(value: &str) -> String {
    format!("{value:?}")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;
    use std::time::{SystemTime, UNIX_EPOCH};

    #[test]
    fn build_generated_page_manifest_from_html_tree() {
        let root = mk_temp_root("manifest");
        let src = root.join("src");

        write_file(&src.join("pages/index.html"), "<h1>Home</h1>");
        write_file(&src.join("pages/about.html"), "<h1>About</h1>");
        write_file(&src.join("pages/posts/[id].html"), "<h1>Post</h1>");

        let entries = build_generated_page_manifest(&src).expect("manifest should build");
        let patterns = entries
            .iter()
            .map(|e| e.pattern.as_str())
            .collect::<Vec<_>>();

        assert!(patterns.contains(&"/"));
        assert!(patterns.contains(&"/about"));
        assert!(patterns.contains(&"/posts/:id"));
        assert!(entries.iter().any(|e| e.symbol == "page_posts_id"));

        cleanup(&root);
    }

    #[test]
    fn render_generated_routes_module_contains_helpers() {
        let entries = vec![GeneratedPageRoute {
            pattern: "/about".to_string(),
            template_path: "/tmp/src/pages/about.html".to_string(),
            symbol: "page_about".to_string(),
        }];

        let source = render_generated_routes_module(&entries);
        assert!(source.contains("pub struct GeneratedPageRoute"));
        assert!(source.contains("GENERATED_PAGE_ROUTES"));
        assert!(source.contains("pub fn generated_routes()"));
        assert!(source.contains("pub fn register_generated_routes"));
        assert!(source.contains("pub fn pilcrow_router"));
        assert!(source.contains("page_about"));
    }

    #[test]
    fn write_generated_routes_module_writes_file() {
        let root = mk_temp_root("write_module");
        let src = root.join("src");
        let out_file = root.join("out/generated_routes.rs");

        write_file(&src.join("pages/index.html"), "<h1>Home</h1>");
        write_file(&src.join("pages/blog/[slug].html"), "<h1>Blog</h1>");

        let entries =
            write_generated_routes_module(&src, &out_file).expect("should write generated file");
        assert_eq!(entries.len(), 2);
        assert!(out_file.exists());

        let generated = fs::read_to_string(&out_file).expect("read generated");
        assert!(generated.contains("/blog/:slug"));
        assert!(generated.contains("page_blog_slug"));

        cleanup(&root);
    }

    fn mk_temp_root(prefix: &str) -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("time")
            .as_nanos();
        let root = std::env::temp_dir().join(format!(
            "pilcrow_routekit_codegen_{}_{}_{}",
            prefix,
            std::process::id(),
            nanos
        ));
        fs::create_dir_all(&root).expect("create temp root");
        root
    }

    fn write_file(path: &Path, contents: &str) {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).expect("create parent");
        }
        fs::write(path, contents).expect("write file");
    }

    fn cleanup(path: &Path) {
        if path.exists() {
            fs::remove_dir_all(path).expect("cleanup temp dir");
        }
    }
}
