use std::collections::HashMap;
use std::fmt::Write as _;
use std::fs;
use std::io;
use std::path::Path;

use proc_macro2::Span;
use quote::ToTokens;
use syn::parse_quote;

use crate::routing::discovery::{build_api_routes, build_page_routes};

/// One generated page route entry for build-time manifests.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedPageRoute {
    pub pattern: String,
    pub template_path: String,
    pub symbol: String,
    pub render_symbol: String,
}

/// One generated API route entry for build-time manifests.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedApiRoute {
    pub pattern: String,
    pub module_path: String,
    pub symbol: String,
}

/// Build an API route manifest from `src/api/**/*.rs`.
pub fn build_generated_api_manifest(
    src_root: impl AsRef<Path>,
) -> io::Result<Vec<GeneratedApiRoute>> {
    build_api_routes(src_root)?
        .into_iter()
        .map(|route| {
            Ok(GeneratedApiRoute {
                pattern: route.pattern,
                module_path: route.module_path,
                symbol: route.symbol,
            })
        })
        .collect()
}

/// Render a Rust module source for discovered API routes.
///
/// The generated module contains:
/// - `GeneratedApiRoute` (borrowed static fields)
/// - `GENERATED_API_ROUTES` const slice
/// - `generated_api_routes()` accessor
/// - `register_generated_api_routes(...)` fold-based helper for framework glue
pub fn render_generated_api_routes_module(entries: &[GeneratedApiRoute]) -> String {
    let mut out = String::new();
    out.push_str("// @generated by pilcrow-routekit. Do not edit manually.\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct GeneratedApiRoute {\n");
    out.push_str("    pub pattern: &'static str,\n");
    out.push_str("    pub module_path: &'static str,\n");
    out.push_str("    pub symbol: &'static str,\n");
    out.push_str("}\n\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub const GENERATED_API_ROUTES: &[GeneratedApiRoute] = &[\n");

    let entries_str: String = entries
        .iter()
        .map(|entry| {
            format!(
                "    GeneratedApiRoute {{ pattern: {}, module_path: {}, symbol: {} }},\n",
                rust_string(&entry.pattern),
                rust_string(&entry.module_path),
                rust_string(&entry.symbol),
            )
        })
        .collect();
    out.push_str(&entries_str);

    out.push_str("];\n\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub fn generated_api_routes() -> &'static [GeneratedApiRoute] {\n");
    out.push_str("    GENERATED_API_ROUTES\n");
    out.push_str("}\n\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub fn register_generated_api_routes<R, F>(router: R, register: F) -> R\n");
    out.push_str("where\n");
    out.push_str("    F: FnMut(R, &'static GeneratedApiRoute) -> R,\n");
    out.push_str("{\n");
    out.push_str("    GENERATED_API_ROUTES.iter().fold(router, register)\n");
    out.push_str("}\n");

    out
}

/// Generate and write the API routes module to the given `out_file` path.
pub fn write_generated_api_routes_module(
    src_root: impl AsRef<Path>,
    out_file: impl AsRef<Path>,
) -> io::Result<Vec<GeneratedApiRoute>> {
    let entries = build_generated_api_manifest(src_root)?;
    let source = render_generated_api_routes_module(&entries);

    let out_file = out_file.as_ref();
    if let Some(parent) = out_file.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(out_file, source)?;

    Ok(entries)
}

/// Input for code-generating one compiled Askama template module.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TemplateCodegenInput {
    pub module_name: String,
    pub render_symbol: String,
    pub source_path: String,
    pub rust_frontmatter: String,
    pub template_source: String,
    /// Ordered layout chain for this page: [outermost_auto_layout, ..., explicit_layout].
    /// Each entry is a layout module name.  Only meaningful for `page_*` modules.
    pub layout_chain: Vec<String>,
}

/// Metadata for one generated template module.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedTemplateEntry {
    pub source_path: String,
    pub module_name: String,
    pub render_symbol: String,
}

/// Metadata about the layout chain's contribution to a page module.
/// Keyed by page module name in `layout_fields_map`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LayoutFieldsInfo {
    /// Ordered from outermost to innermost layout, one entry per layout in the chain
    /// that declares `load()`.  Each entry is `(layout_module_name, field_names)`.
    pub chain: Vec<(String, Vec<String>)>,
    /// Field names belonging to the page's own `Props` (for constructing `__MergedProps`).
    pub page_field_names: Vec<String>,
}

/// Shape of a page's `load()` function. Absent means the page is static.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct LoadSignature {
    /// Whether `load` was declared `async fn`.
    pub is_async: bool,
    /// Whether the return type is `Result<_, _>` / `AppResult<_>`.
    pub returns_result: bool,
    /// Whether the parameter list declares a `PilcrowClient` argument.
    pub wants_client: bool,
    /// Whether the parameter list declares a `Req` argument.
    pub wants_req: bool,
}

/// One discovered named action handler in a page's code-behind.
///
/// Named actions are `pub` fns whose signature matches
/// `pub async fn NAME(req: Req) -> ActionResult` (name other than `load`).
/// The client invokes them by POSTing to the page URL with `?/<name>`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ActionFn {
    /// Function name — also the URL key (`?/<name>`).
    pub name: String,
    pub is_async: bool,
    /// Whether the return type is `Result<_, _>` / `ActionResult`.
    pub returns_result: bool,
    /// Whether the parameter list declares a `Req` argument.
    pub wants_req: bool,
}

/// In-memory generated module + metadata.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedTemplatesModule {
    pub source: String,
    pub entries: Vec<GeneratedTemplateEntry>,
    /// Map from module_name to `Some(sig)` when the frontmatter contains a `load()` fn.
    pub load_map: HashMap<String, Option<LoadSignature>>,
    /// Map from page module_name to layout field info, for pages whose layout has `load()`.
    pub layout_fields_map: HashMap<String, LayoutFieldsInfo>,
    /// Map from page module_name to its list of discovered named action handlers.
    pub action_map: HashMap<String, Vec<ActionFn>>,
}

/// Build a page-route manifest from `src/pages/**/*.html`.
pub fn build_generated_page_manifest(
    src_root: impl AsRef<Path>,
) -> io::Result<Vec<GeneratedPageRoute>> {
    let src_root = src_root.as_ref();
    let pages_dir = src_root.join("pages");
    let pages_dir_norm = normalize_path_text(&pages_dir);

    let routes = build_page_routes(src_root)?;
    let mut generated = routes
        .into_iter()
        .map(|route| {
            let symbol = build_symbol_name(&route.template_path, &pages_dir_norm);
            let render_symbol = format!("render_{symbol}");
            GeneratedPageRoute {
                pattern: route.pattern,
                template_path: route.template_path,
                symbol,
                render_symbol,
            }
        })
        .collect::<Vec<_>>();

    generated.sort_by(|a, b| {
        a.pattern
            .cmp(&b.pattern)
            .then_with(|| a.template_path.cmp(&b.template_path))
    });

    Ok(generated)
}

/// Render a Rust module source for discovered page routes.
///
/// The generated module contains:
/// - `GeneratedPageRoute` (borrowed static fields)
/// - `GENERATED_PAGE_ROUTES` const slice
/// - `generated_routes()` accessor
/// - `register_generated_routes(...)` helper for framework glue
pub fn render_generated_routes_module(entries: &[GeneratedPageRoute]) -> String {
    let mut out = String::new();

    out.push_str("// @generated by pilcrow-routekit. Do not edit manually.\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct GeneratedPageRoute {\n");
    out.push_str("    pub pattern: &'static str,\n");
    out.push_str("    pub template_path: &'static str,\n");
    out.push_str("    pub symbol: &'static str,\n");
    out.push_str("    pub render_symbol: &'static str,\n");
    out.push_str("}\n\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub const GENERATED_PAGE_ROUTES: &[GeneratedPageRoute] = &[\n");

    for entry in entries {
        let pattern = rust_string(&entry.pattern);
        let template_path = rust_string(&entry.template_path);
        let symbol = rust_string(&entry.symbol);
        let render_symbol = rust_string(&entry.render_symbol);
        let _ = writeln!(
            out,
            "    GeneratedPageRoute {{ pattern: {pattern}, template_path: {template_path}, symbol: {symbol}, render_symbol: {render_symbol} }},"
        );
    }

    out.push_str("];\n\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub fn generated_routes() -> &'static [GeneratedPageRoute] {\n");
    out.push_str("    GENERATED_PAGE_ROUTES\n");
    out.push_str("}\n\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub fn register_generated_routes<R, F>(mut router: R, mut register: F) -> R\n");
    out.push_str("where\n");
    out.push_str("    F: FnMut(R, &'static GeneratedPageRoute) -> R,\n");
    out.push_str("{\n");
    out.push_str("    for route in GENERATED_PAGE_ROUTES {\n");
    out.push_str("        router = register(router, route);\n");
    out.push_str("    }\n");
    out.push_str("    router\n");
    out.push_str("}\n");
    out.push('\n');
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub fn pilcrow_router<R, F>(router: R, register: F) -> R\n");
    out.push_str("where\n");
    out.push_str("    F: FnMut(R, &'static GeneratedPageRoute) -> R,\n");
    out.push_str("{\n");
    out.push_str("    register_generated_routes(router, register)\n");
    out.push_str("}\n");

    out
}

/// Generate and write the routes module to the given `out_file` path.
pub fn write_generated_routes_module(
    src_root: impl AsRef<Path>,
    out_file: impl AsRef<Path>,
) -> io::Result<Vec<GeneratedPageRoute>> {
    let entries = build_generated_page_manifest(src_root)?;
    let source = render_generated_routes_module(&entries);

    let out_file = out_file.as_ref();
    if let Some(parent) = out_file.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(out_file, source)?;

    Ok(entries)
}

/// Render a Rust module source for build-time compiled Askama templates.
///
/// Modules are sorted alphabetically before processing. Because `layout_*` sorts
/// before `page_*` before `ui_*`, a single pass correctly collects layout field
/// info before it's needed by any page.
pub fn render_generated_templates_module(
    entries: &[TemplateCodegenInput],
) -> io::Result<GeneratedTemplatesModule> {
    let mut ordered = entries.to_vec();
    ordered.sort_by(|a, b| {
        a.module_name
            .cmp(&b.module_name)
            .then_with(|| a.source_path.cmp(&b.source_path))
    });

    // Accumulates layout fields as we encounter layouts that have load().
    // Keyed by layout module name. Single-pass is safe due to alphabetical ordering.
    let mut layout_fields: HashMap<String, Vec<syn::Field>> = HashMap::new();
    let mut layout_fields_map: HashMap<String, LayoutFieldsInfo> = HashMap::new();

    let mut out = String::new();
    out.push_str("// @generated by pilcrow-routekit. Do not edit manually.\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct GeneratedTemplateEntry {\n");
    out.push_str("    pub source_path: &'static str,\n");
    out.push_str("    pub module_name: &'static str,\n");
    out.push_str("    pub render_symbol: &'static str,\n");
    out.push_str("}\n\n");

    let mut metadata = Vec::with_capacity(ordered.len());
    let mut load_map = HashMap::new();
    let mut action_map: HashMap<String, Vec<ActionFn>> = HashMap::new();

    for entry in &ordered {
        let is_layout = entry.module_name.starts_with("layout_");

        // For pages: inject ALL layouts' fields from the chain that have load().
        let extra_fields: Vec<syn::Field> = if !is_layout {
            entry
                .layout_chain
                .iter()
                .flat_map(|lmod| {
                    layout_fields
                        .get(lmod.as_str())
                        .into_iter()
                        .flat_map(|f| f.iter())
                        .cloned()
                })
                .collect()
        } else {
            vec![]
        };

        let instrumented = instrument_frontmatter(
            &entry.rust_frontmatter,
            &entry.template_source,
            &entry.source_path,
            &extra_fields,
        )?;

        // Store layout's own fields so pages that use this layout can inject them.
        if is_layout && instrumented.load_signature.is_some() {
            layout_fields.insert(
                entry.module_name.clone(),
                instrumented.own_syn_fields.clone(),
            );
        }

        // Record the layout-chain↔page field mapping for use by the app module generator.
        if !extra_fields.is_empty() {
            // Collect one entry per layout in the chain that contributed fields.
            let chain: Vec<(String, Vec<String>)> = entry
                .layout_chain
                .iter()
                .filter_map(|lmod| {
                    layout_fields.get(lmod.as_str()).map(|fields| {
                        (lmod.clone(), named_field_names(fields))
                    })
                })
                .collect();
            if !chain.is_empty() {
                layout_fields_map.insert(
                    entry.module_name.clone(),
                    LayoutFieldsInfo {
                        chain,
                        page_field_names: named_field_names(&instrumented.own_syn_fields),
                    },
                );
            }
        }

        load_map.insert(entry.module_name.clone(), instrumented.load_signature);

        if !instrumented.actions.is_empty() {
            action_map.insert(entry.module_name.clone(), instrumented.actions.clone());
        }

        let module_ident = syn::Ident::new(&entry.module_name, Span::call_site());
        let render_ident = syn::Ident::new(&entry.render_symbol, Span::call_site());

        // When extra_fields is non-empty the module emits __MergedProps for rendering.
        let render_type = if extra_fields.is_empty() { "Props" } else { "__MergedProps" };

        let _ = writeln!(out, "#[allow(dead_code)]");
        let _ = writeln!(out, "pub mod {module_ident} {{");
        for line in instrumented.source.lines() {
            out.push_str("    ");
            out.push_str(line);
            out.push('\n');
        }
        let _ = writeln!(
            out,
            "    pub fn {render_ident}(props: {render_type}) -> Result<String, askama::Error> {{"
        );
        out.push_str("        askama::Template::render(&props)\n");
        out.push_str("    }\n");
        out.push_str("}\n\n");

        metadata.push(GeneratedTemplateEntry {
            source_path: entry.source_path.clone(),
            module_name: module_ident.to_string(),
            render_symbol: render_ident.to_string(),
        });
    }

    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub const GENERATED_TEMPLATES: &[GeneratedTemplateEntry] = &[\n");
    for entry in &metadata {
        let source_path = rust_string(&entry.source_path);
        let module_name = rust_string(&entry.module_name);
        let render_symbol = rust_string(&entry.render_symbol);
        let _ = writeln!(
            out,
            "    GeneratedTemplateEntry {{ source_path: {source_path}, module_name: {module_name}, render_symbol: {render_symbol} }},"
        );
    }
    out.push_str("];\n\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub fn generated_templates() -> &'static [GeneratedTemplateEntry] {\n");
    out.push_str("    GENERATED_TEMPLATES\n");
    out.push_str("}\n");

    Ok(GeneratedTemplatesModule {
        source: out,
        entries: metadata,
        load_map,
        layout_fields_map,
        action_map,
    })
}

/// Output from writing generated templates module.
pub struct WrittenTemplatesOutput {
    pub entries: Vec<GeneratedTemplateEntry>,
    pub load_map: HashMap<String, Option<LoadSignature>>,
    /// Forwarded from `GeneratedTemplatesModule`; passed on to the app module writer.
    pub layout_fields_map: HashMap<String, LayoutFieldsInfo>,
    pub action_map: HashMap<String, Vec<ActionFn>>,
}

/// Generate and write the compiled templates module to `out_file`.
pub fn write_generated_templates_module(
    entries: &[TemplateCodegenInput],
    out_file: impl AsRef<Path>,
) -> io::Result<WrittenTemplatesOutput> {
    let generated = render_generated_templates_module(entries)?;

    let out_file = out_file.as_ref();
    if let Some(parent) = out_file.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(out_file, generated.source)?;

    Ok(WrittenTemplatesOutput {
        entries: generated.entries,
        load_map: generated.load_map,
        layout_fields_map: generated.layout_fields_map,
        action_map: generated.action_map,
    })
}

/// Result of instrumenting a template's Rust frontmatter.
struct InstrumentedFrontmatter {
    source: String,
    load_signature: Option<LoadSignature>,
    /// Named fields declared in the module's own `Props` struct (before any injection).
    own_syn_fields: Vec<syn::Field>,
    /// Named action handlers discovered in the frontmatter (pages only).
    actions: Vec<ActionFn>,
}

/// `extra_fields` contains the named fields from a layout's Props struct when the layout
/// declares `load()`. When non-empty, a `__MergedProps` struct is synthesized in the
/// page module that combines the layout fields with the page's own fields.  The original
/// `Props` struct is kept as-is so the page's own `load()` can still return it.
fn instrument_frontmatter(
    rust_frontmatter: &str,
    template_source: &str,
    source_path: &str,
    extra_fields: &[syn::Field],
) -> io::Result<InstrumentedFrontmatter> {
    let mut file = syn::parse_file(rust_frontmatter).map_err(|err| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("failed to parse rust frontmatter in {source_path}: {err}"),
        )
    })?;

    let mut props_indices = Vec::new();
    for (index, item) in file.items.iter().enumerate() {
        if let syn::Item::Struct(item_struct) = item
            && item_struct.ident == "Props"
        {
            if !matches!(item_struct.vis, syn::Visibility::Public(_)) {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidData,
                    format!("frontmatter in {source_path} must declare `pub struct Props`"),
                ));
            }
            props_indices.push(index);
        }
    }

    if props_indices.len() > 1 {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!(
                "frontmatter in {source_path} declares multiple `Props` structs; expected exactly one"
            ),
        ));
    }

    // Detect `load()` function signature. Absent means the page/component is static.
    let load_signature = file.items.iter().find_map(|item| {
        if let syn::Item::Fn(f) = item
            && f.sig.ident == "load"
        {
            Some(detect_load_signature(&f.sig))
        } else {
            None
        }
    });

    // Discover named action handlers. An action is any `pub` fn in a page's
    // code-behind with an `ActionResult`-shaped return. The fn name is the URL
    // key (`?/<name>`). `load` is excluded — it is the GET handler.
    let in_pages = source_path.contains("/pages/");
    let in_ui = source_path.contains("/ui/");
    let mut actions: Vec<ActionFn> = Vec::new();

    for item in &file.items {
        let syn::Item::Fn(f) = item else { continue };
        let name = f.sig.ident.to_string();
        if name == "load" {
            continue;
        }
        if !matches!(f.vis, syn::Visibility::Public(_)) {
            continue;
        }

        // Helpers use any non-Result return type; only action-shaped fns are considered.
        let returns_result = match &f.sig.output {
            syn::ReturnType::Default => continue,
            syn::ReturnType::Type(_, ty) => {
                let Some(ident) = type_last_ident(ty) else { continue };
                if ident != "Result" && ident != "ActionResult" {
                    continue;
                }
                true
            }
        };

        let is_async = f.sig.asyncness.is_some();
        let wants_req = f.sig.inputs.iter().any(|arg| {
            if let syn::FnArg::Typed(pat) = arg {
                type_last_ident(&pat.ty).map(|id| id == "Req").unwrap_or(false)
            } else {
                false
            }
        });

        if in_ui {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                format!(
                    "action handler `{name}` is not allowed in `{source_path}`; \
                     ui components cannot handle form actions — move it to a page."
                ),
            ));
        }

        // Layouts do not own actions. Skip silently so users can still define
        // helper fns there if their signature happens to match.
        if !in_pages {
            continue;
        }

        if !is_async {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                format!(
                    "action `{name}` in `{source_path}` must be declared `async`.\n\
                     Required signature: pub async fn {name}(req: Req) -> ActionResult"
                ),
            ));
        }
        if !wants_req {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                format!(
                    "action `{name}` in `{source_path}` must take `req: Req` as a parameter.\n\
                     Required signature: pub async fn {name}(req: Req) -> ActionResult"
                ),
            ));
        }

        actions.push(ActionFn { name, is_async, returns_result, wants_req });
    }

    // UI components are Props-only: they display data, they don't fetch it.
    // Layouts CAN have load() — they provide shared data to every page they wrap.
    if in_ui && load_signature.is_some() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!(
                "`load()` is not allowed in `{source_path}`; \
                 ui components are Props-only. \
                 Fetch data in a page (`pages/`) or layout (`layouts/`) and pass it via Props."
            ),
        ));
    }

    // Pages and layouts must use the canonical load() signature so that
    // req.res modifiers (toasts, headers, cookies) are always applied.
    if let Some(ref sig) = load_signature {
        if source_path.contains("/pages/") {
            if !sig.is_async {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidData,
                    format!(
                        "`load()` in `{source_path}` must be declared `async`.\n\
                         Required signature: pub async fn load(req: Req) -> AppResult<Props>"
                    ),
                ));
            }
            if !sig.returns_result {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidData,
                    format!(
                        "`load()` in `{source_path}` must return `AppResult<Props>`.\n\
                         Required signature: pub async fn load(req: Req) -> AppResult<Props>"
                    ),
                ));
            }
            if !sig.wants_req {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidData,
                    format!(
                        "`load()` in `{source_path}` must take `req: Req` as a parameter.\n\
                         Required signature: pub async fn load(req: Req) -> AppResult<Props>"
                    ),
                ));
            }
        }
    }

    let has_manual_default = file.items.iter().any(|item| {
        if let syn::Item::Impl(impl_block) = item {
            if let Some((_, path, _)) = &impl_block.trait_ {
                return path.segments.last().is_some_and(|s| s.ident == "Default");
            }
        }
        false
    });

    for item in &mut file.items {
        match item {
            syn::Item::Struct(item_struct) => ensure_serialize_derive(&mut item_struct.attrs),
            syn::Item::Enum(item_enum) => ensure_serialize_derive(&mut item_enum.attrs),
            syn::Item::Union(item_union) => ensure_serialize_derive(&mut item_union.attrs),
            _ => {}
        }
    }

    // If the user didn't declare `pub struct Props`, synthesize a unit struct.
    let props_index = if let Some(idx) = props_indices.first().copied() {
        idx
    } else {
        file.items.push(parse_quote!(pub struct Props;));
        file.items.len() - 1
    };

    let props_item = file
        .items
        .get_mut(props_index)
        .expect("validated props index should exist");

    let syn::Item::Struct(props_struct) = props_item else {
        unreachable!("validated Props item is not struct")
    };

    // Extract the page's own named fields before any modification.
    let own_syn_fields = extract_named_fields(props_struct);

    if extra_fields.is_empty() {
        // Normal path: Props is used directly for template rendering.
        // Inject Default derive for static pages (no load function).
        if load_signature.is_none()
            && !has_manual_default
            && !has_derive_trait(&props_struct.attrs, &["Default"])
        {
            props_struct.attrs.push(parse_quote!(#[derive(Default)]));
        }
        inject_props_attrs(props_struct, template_source);
    } else {
        // Layout-merge path: Props keeps the page's own fields for load() return.
        // A separate __MergedProps struct (layout fields + page fields) is emitted
        // and used by the render function and the generated handler.
        // serde::Serialize was already added by the loop above; askama::Template
        // goes on __MergedProps only.
        let merged = make_merged_props_struct(extra_fields, &own_syn_fields, template_source)?;
        file.items.push(syn::Item::Struct(merged));
    }

    // Check whether the user's code already imports Req to avoid E0252.
    let has_req_import = file.items.iter().any(|item| {
        if let syn::Item::Use(u) = item {
            let s = u.to_token_stream().to_string();
            // ":: Req" matches `use pilcrow_web::Req`, "{ Req" matches grouped imports.
            s.contains(":: Req") || s.contains("{ Req")
        } else {
            false
        }
    });

    let mut out = String::new();
    out.push_str("#[allow(unused_imports)]\n");
    out.push_str("use pilcrow_web::pilcrow_client::PilcrowClient;\n");
    out.push_str("#[allow(unused_imports)]\n");
    out.push_str("use pilcrow_web::AppResult;\n");
    out.push_str("#[allow(unused_imports)]\n");
    out.push_str("use pilcrow_web::AppResult as PilcrowResult;\n");
    if !has_req_import {
        out.push_str("#[allow(unused_imports)]\n");
        out.push_str("use pilcrow_web::Req;\n");
    }
    out.push_str("#[allow(unused_imports)]\n");
    out.push_str("use pilcrow_web::ActionResult;\n");
    out.push_str("#[allow(unused_imports)]\n");
    out.push_str("use pilcrow_web::redirect;\n");
    for item in file.items {
        out.push_str(&item.into_token_stream().to_string());
        out.push('\n');
    }
    Ok(InstrumentedFrontmatter {
        source: out,
        load_signature,
        own_syn_fields,
        actions,
    })
}

/// Inspect a `load()` `fn` signature to decide how the generated handler
/// should call it: sync vs async, infallible vs `Result`, with/without
/// `PilcrowClient` injection.
fn detect_load_signature(sig: &syn::Signature) -> LoadSignature {
    let is_async = sig.asyncness.is_some();

    let returns_result = match &sig.output {
        syn::ReturnType::Default => false,
        syn::ReturnType::Type(_, ty) => type_last_ident(ty)
            .map(|ident| ident == "Result" || ident == "AppResult" || ident == "PilcrowResult")
            .unwrap_or(false),
    };

    let wants_client = sig.inputs.iter().any(|arg| {
        if let syn::FnArg::Typed(pat) = arg {
            type_last_ident(&pat.ty)
                .map(|ident| ident == "PilcrowClient")
                .unwrap_or(false)
        } else {
            false
        }
    });

    let wants_req = sig.inputs.iter().any(|arg| {
        if let syn::FnArg::Typed(pat) = arg {
            type_last_ident(&pat.ty)
                .map(|ident| ident == "Req")
                .unwrap_or(false)
        } else {
            false
        }
    });

    LoadSignature {
        is_async,
        returns_result,
        wants_client,
        wants_req,
    }
}

/// Return the last path segment ident for a type like `foo::Bar<T>` → `Bar`.
fn type_last_ident(ty: &syn::Type) -> Option<&syn::Ident> {
    let syn::Type::Path(tp) = ty else { return None };
    tp.path.segments.last().map(|seg| &seg.ident)
}

fn inject_props_attrs(props: &mut syn::ItemStruct, template_source: &str) {
    let mut missing_derives = Vec::<syn::Path>::new();
    if !has_derive_trait(&props.attrs, &["askama::Template", "Template"]) {
        missing_derives.push(parse_quote!(askama::Template));
    }
    if !has_derive_trait(&props.attrs, &["serde::Serialize", "Serialize"]) {
        missing_derives.push(parse_quote!(serde::Serialize));
    }

    if !missing_derives.is_empty() {
        props
            .attrs
            .push(parse_quote!(#[derive(#(#missing_derives),*)]));
    }

    if !props
        .attrs
        .iter()
        .any(|attr| attr.path().is_ident("template"))
    {
        let template_lit = syn::LitStr::new(template_source, Span::call_site());
        props
            .attrs
            .push(parse_quote!(#[template(source = #template_lit, ext = "html")]));
    }
}

/// Extract the named fields from a struct's field list.
fn extract_named_fields(item_struct: &syn::ItemStruct) -> Vec<syn::Field> {
    match &item_struct.fields {
        syn::Fields::Named(named) => named.named.iter().cloned().collect(),
        _ => vec![],
    }
}

/// Return the identifier string for each named field.
fn named_field_names(fields: &[syn::Field]) -> Vec<String> {
    fields
        .iter()
        .filter_map(|f| f.ident.as_ref().map(|i| i.to_string()))
        .collect()
}

/// Build the `__MergedProps` struct used when a layout's `load()` contributes fields.
///
/// Fields order: layout fields first, then the page's own fields.
/// Derives `askama::Template` and `serde::Serialize`; attaches the Askama template source.
/// Returns an error if any field name appears in both `extra_fields` and `own_fields`.
fn make_merged_props_struct(
    extra_fields: &[syn::Field],
    own_fields: &[syn::Field],
    template_source: &str,
) -> io::Result<syn::ItemStruct> {
    // Detect field name collisions between layout Props and page Props up front.
    let layout_names = named_field_names(extra_fields);
    let page_names = named_field_names(own_fields);
    for name in &page_names {
        if layout_names.contains(name) {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                format!(
                    "Props field `{name}` is defined in both the layout and the page — \
                     rename one of them to avoid a collision in __MergedProps"
                ),
            ));
        }
    }

    let template_lit = syn::LitStr::new(template_source, Span::call_site());

    // Start with an empty named struct and populate the fields list.
    let mut item: syn::ItemStruct = parse_quote! {
        #[derive(askama::Template, serde::Serialize)]
        #[template(source = #template_lit, ext = "html")]
        pub struct __MergedProps {}
    };

    let syn::Fields::Named(ref mut named_fields) = item.fields else {
        unreachable!("just parsed a named struct")
    };

    for f in extra_fields {
        named_fields.named.push(f.clone());
    }
    for f in own_fields {
        named_fields.named.push(f.clone());
    }

    Ok(item)
}

fn ensure_serialize_derive(attrs: &mut Vec<syn::Attribute>) {
    if has_derive_trait(attrs, &["serde::Serialize", "Serialize"]) {
        return;
    }
    attrs.push(parse_quote!(#[derive(serde::Serialize)]));
}

fn has_derive_trait(attrs: &[syn::Attribute], candidates: &[&str]) -> bool {
    let normalized_candidates = candidates
        .iter()
        .map(|candidate| normalize_derive_path(candidate))
        .collect::<Vec<_>>();

    for attr in attrs {
        if !attr.path().is_ident("derive") {
            continue;
        }

        let tokens = attr.meta.to_token_stream().to_string();
        let normalized_tokens = normalize_derive_path(&tokens);
        if normalized_candidates
            .iter()
            .any(|candidate| normalized_tokens.contains(candidate))
        {
            return true;
        }
    }

    false
}

fn normalize_derive_path(input: &str) -> String {
    input
        .chars()
        .filter(|c| !c.is_whitespace())
        .collect::<String>()
}

fn build_symbol_name(template_path: &str, pages_dir_norm: &str) -> String {
    let path = normalize_path_text(Path::new(template_path));
    let relative = path
        .strip_prefix(pages_dir_norm)
        .unwrap_or(&path)
        .trim_start_matches('/');
    let without_ext = relative.strip_suffix(".html").unwrap_or(relative);

    // Strip layout-group segments `(group)` — they don't appear in URLs or module names.
    let stripped: String = without_ext
        .split('/')
        .filter(|seg| !(seg.starts_with('(') && seg.ends_with(')')))
        .collect::<Vec<_>>()
        .join("/");
    let without_ext = stripped.as_str();

    let mut symbol = String::new();
    let mut prev_underscore = false;
    for ch in without_ext.chars() {
        let mapped = if ch.is_ascii_alphanumeric() {
            ch.to_ascii_lowercase()
        } else {
            '_'
        };

        if mapped == '_' {
            if !prev_underscore {
                symbol.push('_');
            }
            prev_underscore = true;
        } else {
            symbol.push(mapped);
            prev_underscore = false;
        }
    }

    let symbol = symbol.trim_matches('_');
    let symbol = if symbol.is_empty() { "index" } else { symbol };
    format!("page_{symbol}")
}

fn normalize_path_text(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

fn rust_string(value: &str) -> String {
    format!("{value:?}")
}

// ── App module codegen (auto-wired router) ──────────────────

/// Render the API `mod` tree file (`generated_api_mods.rs`).
///
/// Uses `#[path]` attributes pointing to the source directory so that
/// `include!()` from `OUT_DIR` resolves module files correctly.
pub fn render_generated_api_mods(
    api_entries: &[GeneratedApiRoute],
    src_root: &Path,
    has_middleware: bool,
) -> String {
    let mut out = String::new();
    out.push_str("// @generated by pilcrow-routekit. Do not edit manually.\n");

    // Expose src/middleware.rs as `crate::middleware` so the generated shim can call it.
    if has_middleware {
        let middleware_path = src_root.join("middleware.rs");
        let middleware_path_str = middleware_path.to_string_lossy().replace('\\', "/");
        let _ = writeln!(out, "#[path = \"{middleware_path_str}\"]");
        out.push_str("pub mod middleware;\n");
    }

    if api_entries.is_empty() {
        return out;
    }

    // Use #[path] to resolve mod files relative to the actual source tree
    let api_dir = src_root.join("api");
    let api_dir_str = api_dir.to_string_lossy().replace('\\', "/");
    let _ = writeln!(out, "#[path = \"{api_dir_str}\"]");
    out.push_str("pub mod api {\n");

    // Emit leaf modules only (strip the `api::` prefix)
    for entry in api_entries {
        let leaf = entry
            .module_path
            .strip_prefix("api::")
            .unwrap_or(&entry.module_path);
        // For nested modules like "users::id", we need nested mod declarations.
        // For simplicity, only handle single-level for now; nested will use #[path] too.
        if !leaf.contains("::") {
            let _ = writeln!(out, "    pub mod {leaf};");
        }
    }

    // Handle nested API modules
    let nested: Vec<_> = api_entries
        .iter()
        .filter_map(|e| {
            e.module_path
                .strip_prefix("api::")
                .filter(|l| l.contains("::"))
        })
        .collect();

    if !nested.is_empty() {
        // Build sub-tree for nested entries
        #[derive(Default)]
        struct SubNode {
            children: std::collections::BTreeMap<String, SubNode>,
            is_leaf: bool,
        }

        fn sub_insert(node: &mut SubNode, segments: &[&str]) {
            if segments.is_empty() {
                return;
            }
            let child = node.children.entry(segments[0].to_string()).or_default();
            if segments.len() == 1 {
                child.is_leaf = true;
            } else {
                sub_insert(child, &segments[1..]);
            }
        }

        fn sub_emit(node: &SubNode, indent: usize, base_path: &str) -> String {
            let mut out = String::new();
            let pad = "    ".repeat(indent);
            for (name, child) in &node.children {
                let child_path = format!("{base_path}/{name}");
                if child.is_leaf && child.children.is_empty() {
                    let _ = writeln!(out, "{pad}pub mod {name};");
                } else {
                    let _ = writeln!(out, "{pad}#[path = \"{child_path}\"]");
                    let _ = writeln!(out, "{pad}pub mod {name} {{");
                    out.push_str(&sub_emit(child, indent + 1, &child_path));
                    let _ = writeln!(out, "{pad}}}");
                }
            }
            out
        }

        let mut root = SubNode::default();
        for path in &nested {
            let segments: Vec<&str> = path.split("::").collect();
            sub_insert(&mut root, &segments);
        }
        out.push_str(&sub_emit(&root, 1, &api_dir_str));
    }

    out.push_str("}\n");
    out
}

/// Render the full app module that auto-wires all page and API routes.
///
/// This generates `generated_app.rs` containing:
/// - An include of `generated_templates.rs`
/// - A `build_router()` function returning a fully-wired `axum::Router`
///
/// API routes reference modules via `crate::` paths since the mod tree
/// is included separately at crate root level.
///
/// `error_module_for_page` maps each page symbol to its nearest `_error.html` module name.
/// `not_found_module` is the module name of `_not_found.html` (registered as axum fallback).
pub fn render_generated_app_module(
    page_entries: &[GeneratedPageRoute],
    api_entries: &[GeneratedApiRoute],
    load_map: &HashMap<String, Option<LoadSignature>>,
    layout_fields_map: &HashMap<String, LayoutFieldsInfo>,
    error_module_for_page: &HashMap<String, String>,
    not_found_module: Option<&str>,
    loading_module_for_page: &HashMap<String, String>,
    action_map: &HashMap<String, Vec<ActionFn>>,
    has_middleware: bool,
) -> String {
    let mut out = String::new();
    out.push_str("// @generated by pilcrow-routekit. Do not edit manually.\n\n");

    // Include generated templates
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("mod __pilcrow_gen {\n");
    out.push_str("    include!(concat!(env!(\"OUT_DIR\"), \"/generated_templates.rs\"));\n");
    out.push_str("}\n\n");

    // build_router function
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub fn build_router() -> ::pilcrow_web::axum::Router {\n");
    out.push_str("    ::pilcrow_web::axum::Router::new()\n");

    // Page routes
    for entry in page_entries {
        let page_load = load_map.get(&entry.symbol).copied().flatten();
        let chain_info = layout_fields_map.get(&entry.symbol);
        let error_mod = error_module_for_page.get(&entry.symbol).map(String::as_str);
        let loading_mod = loading_module_for_page.get(&entry.symbol).map(String::as_str);
        let page_actions: Option<&Vec<ActionFn>> = action_map.get(&entry.symbol);

        let pattern = rust_string(&entry.pattern);
        let mod_name = &entry.symbol;
        let render_fn = &entry.render_symbol;

        // Collect the active chain: (var_index, layout_mod, field_names, sig) for each layout
        // in the chain that has a load() function.
        let active_chain: Vec<(usize, &str, &Vec<String>, LoadSignature)> = chain_info
            .map(|info| {
                info.chain
                    .iter()
                    .enumerate()
                    .filter_map(|(i, (lmod, fields))| {
                        load_map
                            .get(lmod.as_str())
                            .copied()
                            .flatten()
                            .map(|sig| (i, lmod.as_str(), fields, sig))
                    })
                    .collect()
            })
            .unwrap_or_default();

        let any_layout_load = !active_chain.is_empty();
        let any_layout_client = active_chain.iter().any(|(_, _, _, sig)| sig.wants_client);
        let page_wants_client = page_load.map_or(false, |s| s.wants_client);
        let needs_client = any_layout_client || page_wants_client;

        let any_layout_req = active_chain.iter().any(|(_, _, _, sig)| sig.wants_req);
        let page_wants_req = page_load.map_or(false, |s| s.wants_req);
        let needs_req = any_layout_req || page_wants_req;

        // PilcrowClient is FromRequestParts and must come before Req (FromRequest).
        let closure_args = match (needs_req, needs_client) {
            (true, true) => {
                "client: ::pilcrow_web::PilcrowClient, req: ::pilcrow_web::Req"
            }
            (true, false) => "req: ::pilcrow_web::Req",
            (false, true) => "client: ::pilcrow_web::PilcrowClient",
            (false, false) => "",
        };

        let _ = writeln!(
            out,
            "        .route({pattern}, ::pilcrow_web::axum::routing::get(|{closure_args}| async move {{"
        );

        if !any_layout_load && page_load.is_none() {
            // ── Case 1: static page ─────────────────────────────────────────────
            let _ = writeln!(
                out,
                "            let props = __pilcrow_gen::{mod_name}::Props::default();"
            );
            let _ = writeln!(
                out,
                "            let html = __pilcrow_gen::{mod_name}::{render_fn}(props).expect(\"template render failed\");"
            );
            out.push_str(&emit_loading_append(loading_mod));
            out.push_str("            ::pilcrow_web::axum::response::Html(html)\n");
        } else {
            out.push_str("            use ::pilcrow_web::axum::response::IntoResponse;\n");
            // Clone the response handle before req consumption so load() calls
            // can write to it and we can apply it after rendering.
            if needs_req {
                out.push_str("            let __resp_handle = req.res.clone();\n");
            }

            // ── Layout loads (one per active chain entry, outermost first) ───────
            // When a client is cloned: it must be cloned for every call except the
            // very last consumer (page or last layout).
            let _last_client_consumer_is_page = page_wants_client;
            let layout_client_consumers = active_chain.iter().filter(|(_, _, _, s)| s.wants_client).count();
            let mut client_clones_left = if needs_client {
                let total = layout_client_consumers + if page_wants_client { 1 } else { 0 };
                total.saturating_sub(1)
            } else {
                0
            };

            let layout_req_consumers = active_chain.iter().filter(|(_, _, _, s)| s.wants_req).count();
            let mut req_clones_left = if needs_req {
                let total = layout_req_consumers + if page_wants_req { 1 } else { 0 };
                total.saturating_sub(1)
            } else {
                0
            };

            for (idx, layout_mod, _, lsig) in &active_chain {
                let req_arg = if lsig.wants_req {
                    if req_clones_left > 0 {
                        req_clones_left -= 1;
                        "req.clone()"
                    } else {
                        "req"
                    }
                } else {
                    ""
                };
                let client_arg = if lsig.wants_client {
                    if client_clones_left > 0 {
                        client_clones_left -= 1;
                        "client.clone()"
                    } else {
                        "client"
                    }
                } else {
                    ""
                };
                let layout_call_args = match (req_arg, client_arg) {
                    ("", "") => String::new(),
                    (r, "") => r.to_string(),
                    ("", cl) => cl.to_string(),
                    (r, cl) => format!("{r}, {cl}"),
                };
                let call_expr =
                    format!("__pilcrow_gen::{layout_mod}::load({layout_call_args})");
                let awaited = if lsig.is_async {
                    format!("{call_expr}.await")
                } else {
                    call_expr
                };
                let var = format!("layout_data_{idx}");
                if lsig.returns_result {
                    let _ = writeln!(out, "            let {var} = match {awaited} {{");
                    out.push_str("                Ok(p) => p,\n");
                    out.push_str(&emit_error_branch(error_mod));
                    out.push_str("            };\n");
                } else {
                    let _ = writeln!(out, "            let {var} = {awaited};");
                }
            }

            // ── Page load ────────────────────────────────────────────────────────
            if let Some(psig) = page_load {
                let req_arg = if psig.wants_req {
                    if req_clones_left > 0 {
                        req_clones_left -= 1;
                        "req.clone()"
                    } else {
                        "req"
                    }
                } else {
                    ""
                };
                let client_arg = if psig.wants_client {
                    if client_clones_left > 0 {
                        client_clones_left -= 1;
                        "client.clone()"
                    } else {
                        "client"
                    }
                } else {
                    ""
                };
                let page_call_args = match (req_arg, client_arg) {
                    ("", "") => String::new(),
                    (r, "") => r.to_string(),
                    ("", cl) => cl.to_string(),
                    (r, cl) => format!("{r}, {cl}"),
                };
                let call_expr =
                    format!("__pilcrow_gen::{mod_name}::load({page_call_args})");
                let awaited = if psig.is_async {
                    format!("{call_expr}.await")
                } else {
                    call_expr
                };
                if psig.returns_result {
                    let _ = writeln!(out, "            let page_data = match {awaited} {{");
                    out.push_str("                Ok(p) => p,\n");
                    out.push_str(&emit_error_branch(error_mod));
                    out.push_str("            };\n");
                } else {
                    let _ = writeln!(out, "            let page_data = {awaited};");
                }
            }

            // ── Construct props ──────────────────────────────────────────────────
            if any_layout_load {
                // Layout chain contributed fields → use __MergedProps.
                let info = chain_info.expect("chain_info present when active_chain is non-empty");
                let _ = writeln!(
                    out,
                    "            let props = __pilcrow_gen::{mod_name}::__MergedProps {{"
                );
                // Layout fields: each entry maps to its var (layout_data_{i}).
                for (idx, _, field_names, _) in &active_chain {
                    let var = format!("layout_data_{idx}");
                    for field in *field_names {
                        let _ = writeln!(out, "                {field}: {var}.{field},");
                    }
                }
                // Page fields: from page_data if page has load(), else Default.
                if page_load.is_some() {
                    for field in &info.page_field_names {
                        let _ = writeln!(out, "                {field}: page_data.{field},");
                    }
                } else {
                    for field in &info.page_field_names {
                        let _ = writeln!(out, "                {field}: Default::default(),");
                    }
                }
                out.push_str("            };\n");
            } else {
                // Only page has load() → Props directly.
                let _ = writeln!(out, "            let props = page_data;");
            }

            let _ = writeln!(
                out,
                "            let html = __pilcrow_gen::{mod_name}::{render_fn}(props).expect(\"template render failed\");"
            );
            out.push_str(&emit_loading_append(loading_mod));
            if needs_req {
                out.push_str("            let mut __response = ::pilcrow_web::axum::response::Html(html).into_response();\n");
                out.push_str("            __resp_handle.apply_to(&mut __response);\n");
                out.push_str("            __response\n");
            } else {
                out.push_str(
                    "            ::pilcrow_web::axum::response::Html(html).into_response()\n",
                );
            }
        }

        out.push_str("        }))\n");

        // ── Action POST route (same URL, dispatched by `?/<name>`) ──────────────
        if let Some(actions) = page_actions {
            if !actions.is_empty() {
                out.push_str(&emit_action_route(actions, &entry.pattern, mod_name, error_mod));
            }
        }
    }

    // API routes — reference via crate:: since mod tree is at crate root
    for entry in api_entries {
        let pattern = rust_string(&entry.pattern);
        let mod_path = &entry.module_path;
        let _ = writeln!(out, "        .nest({pattern}, crate::{mod_path}::router())");
    }

    // Not-found fallback — registered last so it matches any unhandled request.
    if let Some(nf_mod) = not_found_module {
        let render_fn = format!("render_{nf_mod}");
        out.push_str("        .fallback(|| async {\n");
        let _ = writeln!(out, "            let props = __pilcrow_gen::{nf_mod}::Props {{}};");
        let _ = writeln!(
            out,
            "            let html = __pilcrow_gen::{nf_mod}::{render_fn}(props)"
        );
        out.push_str(
            "                .unwrap_or_else(|_| \"<h1>404 Not Found</h1>\".to_string());\n",
        );
        out.push_str("            (\n");
        out.push_str("                ::pilcrow_web::StatusCode::NOT_FOUND,\n");
        out.push_str("                ::pilcrow_web::axum::response::Html(html)\n");
        out.push_str("            )\n");
        out.push_str("        })\n");
    }

    // Apply the user's src/middleware.rs as an axum layer if it exists.
    if has_middleware {
        out.push_str("        .layer(::pilcrow_web::axum::middleware::from_fn(__pilcrow_middleware))\n");
    }

    out.push_str("}\n");

    // Generated middleware shim: extracts Req from parts (body stays intact),
    // calls the user's `middleware()`, then forwards to the next handler.
    if has_middleware {
        out.push('\n');
        out.push_str("async fn __pilcrow_middleware(\n");
        out.push_str("    req: ::pilcrow_web::axum::extract::Request,\n");
        out.push_str("    next: ::pilcrow_web::axum::middleware::Next,\n");
        out.push_str(") -> ::pilcrow_web::axum::response::Response {\n");
        out.push_str("    let (mut parts, body) = req.into_parts();\n");
        out.push_str("    let pilcrow_req = ::pilcrow_web::Req::__from_middleware_parts(&mut parts, &()).await;\n");
        out.push_str("    let forwarded = ::pilcrow_web::axum::extract::Request::from_parts(parts, body);\n");
        out.push_str("    let pilcrow_next = ::pilcrow_web::Next::new(next, forwarded);\n");
        out.push_str("    crate::middleware::middleware(pilcrow_req, pilcrow_next).await\n");
        out.push_str("}\n");
    }

    out
}

/// Emit the body that runs when an `AppError` (bound to `e`) needs to be
/// converted into a response. Used from both `Err(e) => { ... }` match arms
/// and from the unknown-action branch of the dispatch table.
///
/// `AppError::Redirect` is handled first — it issues a 303 before any error-page logic.
/// If `error_mod` is `Some`, other errors render the scoped `_error.html` page.
/// Otherwise they fall back to a plain-text 500.
///
/// `req.res` modifiers (toasts, headers, cookies) are applied to both the
/// redirect response and the error-page response so middleware / load-phase
/// side-effects are not silently dropped.
///
/// `indent_levels` sets the number of 4-space indents on the first line; every
/// subsequent line is indented relative to that. This lets callers drop the
/// body into arbitrarily-nested `match` arms.
fn emit_app_error_body(error_mod: Option<&str>, indent_levels: usize) -> String {
    let pad = "    ".repeat(indent_levels);
    let mut s = String::new();

    // Redirect short-circuit
    let _ = writeln!(s, "{pad}if let ::pilcrow_web::AppError::Redirect(ref __path) = e {{");
    let _ = writeln!(s, "{pad}    let mut __redir = ::pilcrow_web::axum::response::Redirect::to(__path).into_response();");
    let _ = writeln!(s, "{pad}    __resp_handle.apply_to(&mut __redir);");
    let _ = writeln!(s, "{pad}    return __redir;");
    let _ = writeln!(s, "{pad}}}");

    if let Some(err_mod) = error_mod {
        let render_fn = format!("render_{err_mod}");
        let _ = writeln!(s, "{pad}let __status = e.status_code();");
        let _ = writeln!(s, "{pad}let __err_props = __pilcrow_gen::{err_mod}::Props {{");
        let _ = writeln!(s, "{pad}    status: __status,");
        let _ = writeln!(s, "{pad}    message: e.to_string(),");
        let _ = writeln!(s, "{pad}}};");
        let _ = writeln!(s, "{pad}let __err_html = __pilcrow_gen::{err_mod}::{render_fn}(__err_props)");
        let _ = writeln!(s, "{pad}    .unwrap_or_else(|_| format!(\"<h1>{{}} Error</h1>\", __status));");
        let _ = writeln!(s, "{pad}let mut __err_resp = (");
        let _ = writeln!(s, "{pad}    ::pilcrow_web::StatusCode::from_u16(__status)");
        let _ = writeln!(s, "{pad}        .unwrap_or(::pilcrow_web::StatusCode::INTERNAL_SERVER_ERROR),");
        let _ = writeln!(s, "{pad}    ::pilcrow_web::axum::response::Html(__err_html)");
        let _ = writeln!(s, "{pad}).into_response();");
        let _ = writeln!(s, "{pad}__resp_handle.apply_to(&mut __err_resp);");
        let _ = writeln!(s, "{pad}return __err_resp;");
    } else {
        let _ = writeln!(s, "{pad}let mut __err_resp = (::pilcrow_web::StatusCode::INTERNAL_SERVER_ERROR, e.to_string()).into_response();");
        let _ = writeln!(s, "{pad}__resp_handle.apply_to(&mut __err_resp);");
        let _ = writeln!(s, "{pad}return __err_resp;");
    }
    s
}

/// Generate the `Err(e) => { ... },` match arm at the load/action call site.
fn emit_error_branch(error_mod: Option<&str>) -> String {
    emit_error_branch_indented(error_mod, 4)
}

/// Same as [`emit_error_branch`] but lets the caller specify the indent level
/// of the `Err(e) =>` line (in 4-space increments). Used for the dispatch-
/// table inner match arms, which sit one level deeper than a top-level match.
fn emit_error_branch_indented(error_mod: Option<&str>, indent_levels: usize) -> String {
    let pad = "    ".repeat(indent_levels);
    let mut s = String::new();
    let _ = writeln!(s, "{pad}Err(e) => {{");
    s.push_str(&emit_app_error_body(error_mod, indent_levels + 1));
    let _ = writeln!(s, "{pad}}},");
    s
}

/// Emit the unknown-action fallback body (bound `e: AppError`, no match wrapper).
fn emit_app_error_branch_body(error_mod: Option<&str>, indent_levels: usize) -> String {
    emit_app_error_body(error_mod, indent_levels)
}

/// Append the loading skeleton `<template>` to the rendered page HTML.
///
/// If `loading_mod` is `Some`, emits a `let html = format!(...)` that wraps the existing
/// `html` binding with `<template id="__pilcrow_loading" hidden>…</template>`.
/// If `None`, emits nothing.
fn emit_loading_append(loading_mod: Option<&str>) -> String {
    if let Some(lmod) = loading_mod {
        let render_fn = format!("render_{lmod}");
        let mut s = String::new();
        let _ = writeln!(
            s,
            "            let __loading_html = __pilcrow_gen::{lmod}::{render_fn}(__pilcrow_gen::{lmod}::Props {{}}).unwrap_or_default();"
        );
        s.push_str("            let html = format!(\"{html}<template id=\\\"__pilcrow_loading\\\" hidden>{__loading_html}</template>\");\n");
        s
    } else {
        String::new()
    }
}

/// Generate a single POST `.route(...)` that dispatches to one of the page's
/// discovered named action handlers.
///
/// The client POSTs to the page URL with `?/<name>` to invoke `fn <name>`.
/// An unknown action returns `404 Not Found`. The dispatch table is static —
/// handlers are discovered at build time by [`instrument_frontmatter`].
fn emit_action_route(
    actions: &[ActionFn],
    pattern: &str,
    mod_name: &str,
    error_mod: Option<&str>,
) -> String {
    let pattern_lit = rust_string(pattern);
    let mut s = String::new();
    let _ = writeln!(
        s,
        "        .route({pattern_lit}, ::pilcrow_web::axum::routing::post(|req: ::pilcrow_web::Req| async move {{"
    );
    s.push_str("            use ::pilcrow_web::axum::response::IntoResponse;\n");
    s.push_str("            let __resp_handle = req.res.clone();\n");
    s.push_str("            let __action = req.action().to_owned();\n");
    s.push_str("            let mut __response = match __action.as_str() {\n");

    for action in actions {
        let name = rust_string(&action.name);
        let fn_ident = &action.name;
        let call_arg = if action.wants_req { "req" } else { "" };
        let call_expr = format!("__pilcrow_gen::{mod_name}::{fn_ident}({call_arg})");
        let awaited = if action.is_async { format!("{call_expr}.await") } else { call_expr };

        let _ = writeln!(s, "                {name} => match {awaited} {{");
        s.push_str("                    Ok(r) => r,\n");
        s.push_str(&emit_error_branch_indented(error_mod, 5));
        s.push_str("                },\n");
    }

    // Unknown action → 404 with the same error-page rendering as other errors.
    s.push_str("                _ => {\n");
    s.push_str("                    let e = ::pilcrow_web::AppError::NotFound(format!(\"unknown action: {}\", __action));\n");
    s.push_str(&emit_app_error_branch_body(error_mod, 5));
    s.push_str("                }\n");
    s.push_str("            };\n");
    s.push_str("            __resp_handle.apply_to(&mut __response);\n");
    s.push_str("            __response\n");
    s.push_str("        }))\n");
    s
}

/// Generate and write the app module and API mods files.
pub fn write_generated_app_module(
    page_entries: &[GeneratedPageRoute],
    api_entries: &[GeneratedApiRoute],
    load_map: &HashMap<String, Option<LoadSignature>>,
    layout_fields_map: &HashMap<String, LayoutFieldsInfo>,
    error_module_for_page: &HashMap<String, String>,
    not_found_module: Option<&str>,
    loading_module_for_page: &HashMap<String, String>,
    action_map: &HashMap<String, Vec<ActionFn>>,
    has_middleware: bool,
    src_root: &Path,
    out_dir: impl AsRef<Path>,
) -> io::Result<()> {
    let out_dir = out_dir.as_ref();
    fs::create_dir_all(out_dir)?;

    let app_source = render_generated_app_module(
        page_entries,
        api_entries,
        load_map,
        layout_fields_map,
        error_module_for_page,
        not_found_module,
        loading_module_for_page,
        action_map,
        has_middleware,
    );
    fs::write(out_dir.join("generated_app.rs"), app_source)?;

    let mods_source = render_generated_api_mods(api_entries, src_root, has_middleware);
    fs::write(out_dir.join("generated_api_mods.rs"), mods_source)?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;
    use std::time::{SystemTime, UNIX_EPOCH};

    #[test]
    fn build_generated_page_manifest_from_html_tree() {
        let root = mk_temp_root("manifest");
        let src = root.join("src");

        write_file(&src.join("pages/index.html"), "<h1>Home</h1>");
        write_file(&src.join("pages/about.html"), "<h1>About</h1>");
        write_file(&src.join("pages/posts/[id].html"), "<h1>Post</h1>");

        let entries = build_generated_page_manifest(&src).expect("manifest should build");
        let patterns = entries
            .iter()
            .map(|e| e.pattern.as_str())
            .collect::<Vec<_>>();

        assert!(patterns.contains(&"/"));
        assert!(patterns.contains(&"/about"));
        assert!(patterns.contains(&"/posts/:id"));
        assert!(entries.iter().any(|e| e.symbol == "page_posts_id"));
        assert!(
            entries
                .iter()
                .any(|e| e.render_symbol == "render_page_posts_id")
        );

        cleanup(&root);
    }

    #[test]
    fn render_generated_routes_module_contains_helpers() {
        let entries = vec![GeneratedPageRoute {
            pattern: "/about".to_string(),
            template_path: "/tmp/src/pages/about.html".to_string(),
            symbol: "page_about".to_string(),
            render_symbol: "render_page_about".to_string(),
        }];

        let source = render_generated_routes_module(&entries);
        assert!(source.contains("pub struct GeneratedPageRoute"));
        assert!(source.contains("GENERATED_PAGE_ROUTES"));
        assert!(source.contains("pub fn generated_routes()"));
        assert!(source.contains("pub fn register_generated_routes"));
        assert!(source.contains("pub fn pilcrow_router"));
        assert!(source.contains("page_about"));
        assert!(source.contains("render_page_about"));
    }

    #[test]
    fn write_generated_routes_module_writes_file() {
        let root = mk_temp_root("write_module");
        let src = root.join("src");
        let out_file = root.join("out/generated_routes.rs");

        write_file(&src.join("pages/index.html"), "<h1>Home</h1>");
        write_file(&src.join("pages/blog/[slug].html"), "<h1>Blog</h1>");

        let entries =
            write_generated_routes_module(&src, &out_file).expect("should write generated file");
        assert_eq!(entries.len(), 2);
        assert!(out_file.exists());

        let generated = fs::read_to_string(&out_file).expect("read generated");
        assert!(generated.contains("/blog/:slug"));
        assert!(generated.contains("page_blog_slug"));
        assert!(generated.contains("render_page_blog_slug"));

        cleanup(&root);
    }

    #[test]
    fn render_generated_templates_module_instruments_props_and_render_fn() {
        let generated = render_generated_templates_module(&[TemplateCodegenInput {
            module_name: "page_index".to_string(),
            render_symbol: "render_page_index".to_string(),
            source_path: "/tmp/src/pages/index.html".to_string(),
            rust_frontmatter: "pub struct Props { pub title: String }".to_string(),
            template_source: "<h1>{{ title }}</h1>".to_string(),
            layout_chain: vec![],
        }])
        .expect("template module should generate");

        assert_eq!(generated.entries.len(), 1);
        assert!(generated.source.contains("pub mod page_index"));
        assert!(generated.source.contains("askama :: Template"));
        assert!(generated.source.contains("serde :: Serialize"));
        assert!(generated.source.contains("<h1>{{ title }}</h1>"));
        assert!(generated.source.contains("pub fn render_page_index"));
        assert!(generated.source.contains("GENERATED_TEMPLATES"));
    }

    #[test]
    fn render_generated_templates_module_synthesizes_missing_props() {
        let generated = render_generated_templates_module(&[TemplateCodegenInput {
            module_name: "page_index".to_string(),
            render_symbol: "render_page_index".to_string(),
            source_path: "/tmp/src/pages/index.html".to_string(),
            rust_frontmatter: "pub fn helper() {}".to_string(),
            template_source: "<h1>Home</h1>".to_string(),
            layout_chain: vec![],
        }])
        .expect("synthesized Props should compile");

        // A unit struct is synthesized when the frontmatter omits Props.
        assert!(generated.source.contains("pub struct Props"));
        assert!(generated.source.contains("template (source"));
        // Static page (no load fn) → entry is None.
        assert_eq!(generated.load_map.get("page_index"), Some(&None));
    }

    #[test]
    fn render_generated_templates_module_fails_with_duplicate_props() {
        let err = render_generated_templates_module(&[TemplateCodegenInput {
            module_name: "page_index".to_string(),
            render_symbol: "render_page_index".to_string(),
            source_path: "/tmp/src/pages/index.html".to_string(),
            rust_frontmatter: "pub struct Props {} pub struct Props { pub id: i64 }".to_string(),
            template_source: "<h1>Home</h1>".to_string(),
            layout_chain: vec![],
        }])
        .expect_err("duplicate props should fail");

        assert_eq!(err.kind(), io::ErrorKind::InvalidData);
        assert!(
            err.to_string()
                .contains("declares multiple `Props` structs")
        );
    }

    fn mk_temp_root(prefix: &str) -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("time")
            .as_nanos();
        let root = std::env::temp_dir().join(format!(
            "pilcrow_routekit_codegen_{}_{}_{}",
            prefix,
            std::process::id(),
            nanos
        ));
        fs::create_dir_all(&root).expect("create temp root");
        root
    }

    fn write_file(path: &Path, contents: &str) {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).expect("create parent");
        }
        fs::write(path, contents).expect("write file");
    }

    fn cleanup(path: &Path) {
        if path.exists() {
            fs::remove_dir_all(path).expect("cleanup temp dir");
        }
    }

    #[test]
    fn build_generated_api_manifest_from_rs_tree() {
        let root = mk_temp_root("api_manifest");
        let src = root.join("src");

        write_file(&src.join("api/todos.rs"), "pub fn router() {}");
        write_file(&src.join("api/users/[id].rs"), "pub fn router() {}");

        let entries = build_generated_api_manifest(&src).expect("manifest should build");
        let patterns = entries
            .iter()
            .map(|e| e.pattern.as_str())
            .collect::<Vec<_>>();

        assert!(patterns.contains(&"/api/todos"));
        assert!(patterns.contains(&"/api/users/:id"));
        assert!(entries.iter().any(|e| e.symbol == "api_todos"));
        assert!(entries.iter().any(|e| e.symbol == "api_users_id"));
        assert!(entries.iter().any(|e| e.module_path == "api::users::id"));

        cleanup(&root);
    }

    #[test]
    fn render_generated_api_routes_module_contains_helpers() {
        let entries = vec![GeneratedApiRoute {
            pattern: "/api/todos".to_string(),
            module_path: "api::todos".to_string(),
            symbol: "api_todos".to_string(),
        }];

        let source = render_generated_api_routes_module(&entries);
        assert!(source.contains("pub struct GeneratedApiRoute"));
        assert!(source.contains("GENERATED_API_ROUTES"));
        assert!(source.contains("pub fn generated_api_routes()"));
        assert!(source.contains("pub fn register_generated_api_routes"));
        assert!(source.contains("GENERATED_API_ROUTES.iter().fold(router, register)"));
        assert!(source.contains("api_todos"));
        assert!(source.contains("/api/todos"));
    }

    #[test]
    fn write_generated_api_routes_module_writes_file() {
        let root = mk_temp_root("write_api_module");
        let src = root.join("src");
        let out_file = root.join("out/generated_api_routes.rs");

        write_file(&src.join("api/todos.rs"), "pub fn router() {}");
        write_file(&src.join("api/users/[id].rs"), "pub fn router() {}");

        let entries = write_generated_api_routes_module(&src, &out_file)
            .expect("should write generated file");
        assert_eq!(entries.len(), 2);
        assert!(out_file.exists());

        let generated = fs::read_to_string(&out_file).expect("read generated");
        assert!(generated.contains("/api/todos"));
        assert!(generated.contains("/api/users/:id"));
        assert!(generated.contains("api_users_id"));

        cleanup(&root);
    }

    #[test]
    fn emit_action_route_emits_named_dispatch_table() {
        let actions = vec![
            ActionFn {
                name: "create".to_string(),
                is_async: true,
                returns_result: true,
                wants_req: true,
            },
            ActionFn {
                name: "delete".to_string(),
                is_async: true,
                returns_result: true,
                wants_req: true,
            },
        ];

        let source = emit_action_route(&actions, "/items", "page_items", None);

        // POST handler shape
        assert!(source.contains(".route(\"/items\""));
        assert!(source.contains("::pilcrow_web::axum::routing::post"));
        assert!(source.contains("let __resp_handle = req.res.clone();"));
        assert!(source.contains("let __action = req.action().to_owned();"));
        assert!(source.contains("match __action.as_str()"));

        // Per-action dispatch arms calling the code-behind fns
        assert!(source.contains("\"create\" => match __pilcrow_gen::page_items::create(req).await"));
        assert!(source.contains("\"delete\" => match __pilcrow_gen::page_items::delete(req).await"));

        // Unknown action → 404 via AppError::NotFound
        assert!(source.contains("_ => {"));
        assert!(source.contains("::pilcrow_web::AppError::NotFound"));
        assert!(source.contains("unknown action:"));

        // Redirect short-circuit still present and __resp_handle applied
        assert!(source.contains("::pilcrow_web::AppError::Redirect"));
        assert!(source.contains("__resp_handle.apply_to(&mut __response);"));
    }

    #[test]
    fn emit_action_route_uses_custom_error_module_when_provided() {
        let actions = vec![ActionFn {
            name: "update".to_string(),
            is_async: true,
            returns_result: true,
            wants_req: true,
        }];

        let source = emit_action_route(&actions, "/settings", "page_settings", Some("error_root"));

        // Error-page render goes through the provided error module
        assert!(source.contains("__pilcrow_gen::error_root::Props"));
        assert!(source.contains("__pilcrow_gen::error_root::render_error_root"));
        // And __resp_handle is applied to the error response too
        assert!(source.contains("__resp_handle.apply_to(&mut __err_resp);"));
    }
}
