use std::fmt::Write as _;
use std::fs;
use std::io;
use std::path::Path;

use proc_macro2::Span;
use quote::ToTokens;
use syn::parse_quote;

use crate::routing::discovery::{build_api_routes, build_page_routes};

/// One generated page route entry for build-time manifests.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedPageRoute {
    pub pattern: String,
    pub template_path: String,
    pub symbol: String,
    pub render_symbol: String,
}

/// One generated API route entry for build-time manifests.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedApiRoute {
    pub pattern: String,
    pub module_path: String,
    pub symbol: String,
}

/// Build an API route manifest from `src/api/**/*.rs`.
pub fn build_generated_api_manifest(
    src_root: impl AsRef<Path>,
) -> io::Result<Vec<GeneratedApiRoute>> {
    build_api_routes(src_root)?
        .into_iter()
        .map(|route| {
            Ok(GeneratedApiRoute {
                pattern: route.pattern,
                module_path: route.module_path,
                symbol: route.symbol,
            })
        })
        .collect()
}

/// Render a Rust module source for discovered API routes.
///
/// The generated module contains:
/// - `GeneratedApiRoute` (borrowed static fields)
/// - `GENERATED_API_ROUTES` const slice
/// - `generated_api_routes()` accessor
/// - `register_generated_api_routes(...)` fold-based helper for framework glue
pub fn render_generated_api_routes_module(entries: &[GeneratedApiRoute]) -> String {
    let mut out = String::new();
    out.push_str("// @generated by pilcrow-routekit. Do not edit manually.\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct GeneratedApiRoute {\n");
    out.push_str("    pub pattern: &'static str,\n");
    out.push_str("    pub module_path: &'static str,\n");
    out.push_str("    pub symbol: &'static str,\n");
    out.push_str("}\n\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub const GENERATED_API_ROUTES: &[GeneratedApiRoute] = &[\n");

    let entries_str: String = entries
        .iter()
        .map(|entry| {
            format!(
                "    GeneratedApiRoute {{ pattern: {}, module_path: {}, symbol: {} }},\n",
                rust_string(&entry.pattern),
                rust_string(&entry.module_path),
                rust_string(&entry.symbol),
            )
        })
        .collect();
    out.push_str(&entries_str);

    out.push_str("];\n\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub fn generated_api_routes() -> &'static [GeneratedApiRoute] {\n");
    out.push_str("    GENERATED_API_ROUTES\n");
    out.push_str("}\n\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub fn register_generated_api_routes<R, F>(router: R, register: F) -> R\n");
    out.push_str("where\n");
    out.push_str("    F: FnMut(R, &'static GeneratedApiRoute) -> R,\n");
    out.push_str("{\n");
    out.push_str("    GENERATED_API_ROUTES.iter().fold(router, register)\n");
    out.push_str("}\n");

    out
}

/// Generate and write the API routes module to the given `out_file` path.
pub fn write_generated_api_routes_module(
    src_root: impl AsRef<Path>,
    out_file: impl AsRef<Path>,
) -> io::Result<Vec<GeneratedApiRoute>> {
    let entries = build_generated_api_manifest(src_root)?;
    let source = render_generated_api_routes_module(&entries);

    let out_file = out_file.as_ref();
    if let Some(parent) = out_file.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(out_file, source)?;

    Ok(entries)
}

/// Input for code-generating one compiled Askama template module.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TemplateCodegenInput {
    pub module_name: String,
    pub render_symbol: String,
    pub source_path: String,
    pub rust_frontmatter: String,
    pub template_source: String,
}

/// Metadata for one generated template module.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedTemplateEntry {
    pub source_path: String,
    pub module_name: String,
    pub render_symbol: String,
}

/// In-memory generated module + metadata.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedTemplatesModule {
    pub source: String,
    pub entries: Vec<GeneratedTemplateEntry>,
}

/// Build a page-route manifest from `src/pages/**/*.html`.
pub fn build_generated_page_manifest(
    src_root: impl AsRef<Path>,
) -> io::Result<Vec<GeneratedPageRoute>> {
    let src_root = src_root.as_ref();
    let pages_dir = src_root.join("pages");
    let pages_dir_norm = normalize_path_text(&pages_dir);

    let routes = build_page_routes(src_root)?;
    let mut generated = routes
        .into_iter()
        .map(|route| {
            let symbol = build_symbol_name(&route.template_path, &pages_dir_norm);
            let render_symbol = format!("render_{symbol}");
            GeneratedPageRoute {
                pattern: route.pattern,
                template_path: route.template_path,
                symbol,
                render_symbol,
            }
        })
        .collect::<Vec<_>>();

    generated.sort_by(|a, b| {
        a.pattern
            .cmp(&b.pattern)
            .then_with(|| a.template_path.cmp(&b.template_path))
    });

    Ok(generated)
}

/// Render a Rust module source for discovered page routes.
///
/// The generated module contains:
/// - `GeneratedPageRoute` (borrowed static fields)
/// - `GENERATED_PAGE_ROUTES` const slice
/// - `generated_routes()` accessor
/// - `register_generated_routes(...)` helper for framework glue
pub fn render_generated_routes_module(entries: &[GeneratedPageRoute]) -> String {
    let mut out = String::new();

    out.push_str("// @generated by pilcrow-routekit. Do not edit manually.\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct GeneratedPageRoute {\n");
    out.push_str("    pub pattern: &'static str,\n");
    out.push_str("    pub template_path: &'static str,\n");
    out.push_str("    pub symbol: &'static str,\n");
    out.push_str("    pub render_symbol: &'static str,\n");
    out.push_str("}\n\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub const GENERATED_PAGE_ROUTES: &[GeneratedPageRoute] = &[\n");

    for entry in entries {
        let pattern = rust_string(&entry.pattern);
        let template_path = rust_string(&entry.template_path);
        let symbol = rust_string(&entry.symbol);
        let render_symbol = rust_string(&entry.render_symbol);
        let _ = writeln!(
            out,
            "    GeneratedPageRoute {{ pattern: {pattern}, template_path: {template_path}, symbol: {symbol}, render_symbol: {render_symbol} }},"
        );
    }

    out.push_str("];\n\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub fn generated_routes() -> &'static [GeneratedPageRoute] {\n");
    out.push_str("    GENERATED_PAGE_ROUTES\n");
    out.push_str("}\n\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub fn register_generated_routes<R, F>(mut router: R, mut register: F) -> R\n");
    out.push_str("where\n");
    out.push_str("    F: FnMut(R, &'static GeneratedPageRoute) -> R,\n");
    out.push_str("{\n");
    out.push_str("    for route in GENERATED_PAGE_ROUTES {\n");
    out.push_str("        router = register(router, route);\n");
    out.push_str("    }\n");
    out.push_str("    router\n");
    out.push_str("}\n");
    out.push('\n');
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub fn pilcrow_router<R, F>(router: R, register: F) -> R\n");
    out.push_str("where\n");
    out.push_str("    F: FnMut(R, &'static GeneratedPageRoute) -> R,\n");
    out.push_str("{\n");
    out.push_str("    register_generated_routes(router, register)\n");
    out.push_str("}\n");

    out
}

/// Generate and write the routes module to the given `out_file` path.
pub fn write_generated_routes_module(
    src_root: impl AsRef<Path>,
    out_file: impl AsRef<Path>,
) -> io::Result<Vec<GeneratedPageRoute>> {
    let entries = build_generated_page_manifest(src_root)?;
    let source = render_generated_routes_module(&entries);

    let out_file = out_file.as_ref();
    if let Some(parent) = out_file.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(out_file, source)?;

    Ok(entries)
}

/// Render a Rust module source for build-time compiled Askama templates.
pub fn render_generated_templates_module(
    entries: &[TemplateCodegenInput],
) -> io::Result<GeneratedTemplatesModule> {
    let mut ordered = entries.to_vec();
    ordered.sort_by(|a, b| {
        a.module_name
            .cmp(&b.module_name)
            .then_with(|| a.source_path.cmp(&b.source_path))
    });

    let mut out = String::new();
    out.push_str("// @generated by pilcrow-routekit. Do not edit manually.\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct GeneratedTemplateEntry {\n");
    out.push_str("    pub source_path: &'static str,\n");
    out.push_str("    pub module_name: &'static str,\n");
    out.push_str("    pub render_symbol: &'static str,\n");
    out.push_str("}\n\n");

    let mut metadata = Vec::with_capacity(ordered.len());

    for entry in ordered {
        let frontmatter = instrument_frontmatter(
            &entry.rust_frontmatter,
            &entry.template_source,
            &entry.source_path,
        )?;
        let module_ident = syn::Ident::new(&entry.module_name, Span::call_site());
        let render_ident = syn::Ident::new(&entry.render_symbol, Span::call_site());

        let _ = writeln!(out, "#[allow(dead_code)]");
        let _ = writeln!(out, "pub mod {module_ident} {{");
        for line in frontmatter.lines() {
            out.push_str("    ");
            out.push_str(line);
            out.push('\n');
        }
        let _ = writeln!(
            out,
            "    pub fn {render_ident}(props: Props) -> Result<String, askama::Error> {{"
        );
        out.push_str("        askama::Template::render(&props)\n");
        out.push_str("    }\n");
        out.push_str("}\n\n");

        metadata.push(GeneratedTemplateEntry {
            source_path: entry.source_path,
            module_name: module_ident.to_string(),
            render_symbol: render_ident.to_string(),
        });
    }

    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub const GENERATED_TEMPLATES: &[GeneratedTemplateEntry] = &[\n");
    for entry in &metadata {
        let source_path = rust_string(&entry.source_path);
        let module_name = rust_string(&entry.module_name);
        let render_symbol = rust_string(&entry.render_symbol);
        let _ = writeln!(
            out,
            "    GeneratedTemplateEntry {{ source_path: {source_path}, module_name: {module_name}, render_symbol: {render_symbol} }},"
        );
    }
    out.push_str("];\n\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub fn generated_templates() -> &'static [GeneratedTemplateEntry] {\n");
    out.push_str("    GENERATED_TEMPLATES\n");
    out.push_str("}\n");

    Ok(GeneratedTemplatesModule {
        source: out,
        entries: metadata,
    })
}

/// Generate and write the compiled templates module to `out_file`.
pub fn write_generated_templates_module(
    entries: &[TemplateCodegenInput],
    out_file: impl AsRef<Path>,
) -> io::Result<Vec<GeneratedTemplateEntry>> {
    let generated = render_generated_templates_module(entries)?;

    let out_file = out_file.as_ref();
    if let Some(parent) = out_file.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(out_file, generated.source)?;

    Ok(generated.entries)
}

fn instrument_frontmatter(
    rust_frontmatter: &str,
    template_source: &str,
    source_path: &str,
) -> io::Result<String> {
    let mut file = syn::parse_file(rust_frontmatter).map_err(|err| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("failed to parse rust frontmatter in {source_path}: {err}"),
        )
    })?;

    let mut props_indices = Vec::new();
    for (index, item) in file.items.iter().enumerate() {
        if let syn::Item::Struct(item_struct) = item
            && item_struct.ident == "Props"
        {
            if !matches!(item_struct.vis, syn::Visibility::Public(_)) {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidData,
                    format!("frontmatter in {source_path} must declare `pub struct Props`"),
                ));
            }
            props_indices.push(index);
        }
    }

    if props_indices.is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("frontmatter in {source_path} is missing required `pub struct Props`"),
        ));
    }
    if props_indices.len() > 1 {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!(
                "frontmatter in {source_path} declares multiple `Props` structs; expected exactly one"
            ),
        ));
    }

    for item in &mut file.items {
        match item {
            syn::Item::Struct(item_struct) => ensure_serialize_derive(&mut item_struct.attrs),
            syn::Item::Enum(item_enum) => ensure_serialize_derive(&mut item_enum.attrs),
            syn::Item::Union(item_union) => ensure_serialize_derive(&mut item_union.attrs),
            _ => {}
        }
    }

    let props_index = props_indices[0];
    let props_item = file
        .items
        .get_mut(props_index)
        .expect("validated props index should exist");

    let syn::Item::Struct(props_struct) = props_item else {
        unreachable!("validated Props item is not struct")
    };

    inject_props_attrs(props_struct, template_source);

    let mut out = String::new();
    for item in file.items {
        out.push_str(&item.into_token_stream().to_string());
        out.push('\n');
    }

    Ok(out)
}

fn inject_props_attrs(props: &mut syn::ItemStruct, template_source: &str) {
    let mut missing_derives = Vec::<syn::Path>::new();
    if !has_derive_trait(&props.attrs, &["askama::Template", "Template"]) {
        missing_derives.push(parse_quote!(askama::Template));
    }
    if !has_derive_trait(&props.attrs, &["serde::Serialize", "Serialize"]) {
        missing_derives.push(parse_quote!(serde::Serialize));
    }

    if !missing_derives.is_empty() {
        props
            .attrs
            .push(parse_quote!(#[derive(#(#missing_derives),*)]));
    }

    if !props
        .attrs
        .iter()
        .any(|attr| attr.path().is_ident("template"))
    {
        let template_lit = syn::LitStr::new(template_source, Span::call_site());
        props
            .attrs
            .push(parse_quote!(#[template(source = #template_lit, ext = "html")]));
    }
}

fn ensure_serialize_derive(attrs: &mut Vec<syn::Attribute>) {
    if has_derive_trait(attrs, &["serde::Serialize", "Serialize"]) {
        return;
    }
    attrs.push(parse_quote!(#[derive(serde::Serialize)]));
}

fn has_derive_trait(attrs: &[syn::Attribute], candidates: &[&str]) -> bool {
    let normalized_candidates = candidates
        .iter()
        .map(|candidate| normalize_derive_path(candidate))
        .collect::<Vec<_>>();

    for attr in attrs {
        if !attr.path().is_ident("derive") {
            continue;
        }

        let tokens = attr.meta.to_token_stream().to_string();
        let normalized_tokens = normalize_derive_path(&tokens);
        if normalized_candidates
            .iter()
            .any(|candidate| normalized_tokens.contains(candidate))
        {
            return true;
        }
    }

    false
}

fn normalize_derive_path(input: &str) -> String {
    input
        .chars()
        .filter(|c| !c.is_whitespace())
        .collect::<String>()
}

fn build_symbol_name(template_path: &str, pages_dir_norm: &str) -> String {
    let path = normalize_path_text(Path::new(template_path));
    let relative = path
        .strip_prefix(pages_dir_norm)
        .unwrap_or(&path)
        .trim_start_matches('/');
    let without_ext = relative.strip_suffix(".html").unwrap_or(relative);

    let mut symbol = String::new();
    let mut prev_underscore = false;
    for ch in without_ext.chars() {
        let mapped = if ch.is_ascii_alphanumeric() {
            ch.to_ascii_lowercase()
        } else {
            '_'
        };

        if mapped == '_' {
            if !prev_underscore {
                symbol.push('_');
            }
            prev_underscore = true;
        } else {
            symbol.push(mapped);
            prev_underscore = false;
        }
    }

    let symbol = symbol.trim_matches('_');
    let symbol = if symbol.is_empty() { "index" } else { symbol };
    format!("page_{symbol}")
}

fn normalize_path_text(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

fn rust_string(value: &str) -> String {
    format!("{value:?}")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;
    use std::time::{SystemTime, UNIX_EPOCH};

    #[test]
    fn build_generated_page_manifest_from_html_tree() {
        let root = mk_temp_root("manifest");
        let src = root.join("src");

        write_file(&src.join("pages/index.html"), "<h1>Home</h1>");
        write_file(&src.join("pages/about.html"), "<h1>About</h1>");
        write_file(&src.join("pages/posts/[id].html"), "<h1>Post</h1>");

        let entries = build_generated_page_manifest(&src).expect("manifest should build");
        let patterns = entries
            .iter()
            .map(|e| e.pattern.as_str())
            .collect::<Vec<_>>();

        assert!(patterns.contains(&"/"));
        assert!(patterns.contains(&"/about"));
        assert!(patterns.contains(&"/posts/:id"));
        assert!(entries.iter().any(|e| e.symbol == "page_posts_id"));
        assert!(
            entries
                .iter()
                .any(|e| e.render_symbol == "render_page_posts_id")
        );

        cleanup(&root);
    }

    #[test]
    fn render_generated_routes_module_contains_helpers() {
        let entries = vec![GeneratedPageRoute {
            pattern: "/about".to_string(),
            template_path: "/tmp/src/pages/about.html".to_string(),
            symbol: "page_about".to_string(),
            render_symbol: "render_page_about".to_string(),
        }];

        let source = render_generated_routes_module(&entries);
        assert!(source.contains("pub struct GeneratedPageRoute"));
        assert!(source.contains("GENERATED_PAGE_ROUTES"));
        assert!(source.contains("pub fn generated_routes()"));
        assert!(source.contains("pub fn register_generated_routes"));
        assert!(source.contains("pub fn pilcrow_router"));
        assert!(source.contains("page_about"));
        assert!(source.contains("render_page_about"));
    }

    #[test]
    fn write_generated_routes_module_writes_file() {
        let root = mk_temp_root("write_module");
        let src = root.join("src");
        let out_file = root.join("out/generated_routes.rs");

        write_file(&src.join("pages/index.html"), "<h1>Home</h1>");
        write_file(&src.join("pages/blog/[slug].html"), "<h1>Blog</h1>");

        let entries =
            write_generated_routes_module(&src, &out_file).expect("should write generated file");
        assert_eq!(entries.len(), 2);
        assert!(out_file.exists());

        let generated = fs::read_to_string(&out_file).expect("read generated");
        assert!(generated.contains("/blog/:slug"));
        assert!(generated.contains("page_blog_slug"));
        assert!(generated.contains("render_page_blog_slug"));

        cleanup(&root);
    }

    #[test]
    fn render_generated_templates_module_instruments_props_and_render_fn() {
        let generated = render_generated_templates_module(&[TemplateCodegenInput {
            module_name: "page_index".to_string(),
            render_symbol: "render_page_index".to_string(),
            source_path: "/tmp/src/pages/index.html".to_string(),
            rust_frontmatter: "pub struct Props { pub title: String }".to_string(),
            template_source: "<h1>{{ title }}</h1>".to_string(),
        }])
        .expect("template module should generate");

        assert_eq!(generated.entries.len(), 1);
        assert!(generated.source.contains("pub mod page_index"));
        assert!(generated.source.contains("askama :: Template"));
        assert!(generated.source.contains("serde :: Serialize"));
        assert!(generated.source.contains("<h1>{{ title }}</h1>"));
        assert!(generated.source.contains("pub fn render_page_index"));
        assert!(generated.source.contains("GENERATED_TEMPLATES"));
    }

    #[test]
    fn render_generated_templates_module_fails_without_props() {
        let err = render_generated_templates_module(&[TemplateCodegenInput {
            module_name: "page_index".to_string(),
            render_symbol: "render_page_index".to_string(),
            source_path: "/tmp/src/pages/index.html".to_string(),
            rust_frontmatter: "pub fn helper() {}".to_string(),
            template_source: "<h1>Home</h1>".to_string(),
        }])
        .expect_err("missing props should fail");

        assert_eq!(err.kind(), io::ErrorKind::InvalidData);
        assert!(
            err.to_string()
                .contains("missing required `pub struct Props`")
        );
    }

    #[test]
    fn render_generated_templates_module_fails_with_duplicate_props() {
        let err = render_generated_templates_module(&[TemplateCodegenInput {
            module_name: "page_index".to_string(),
            render_symbol: "render_page_index".to_string(),
            source_path: "/tmp/src/pages/index.html".to_string(),
            rust_frontmatter: "pub struct Props {} pub struct Props { pub id: i64 }".to_string(),
            template_source: "<h1>Home</h1>".to_string(),
        }])
        .expect_err("duplicate props should fail");

        assert_eq!(err.kind(), io::ErrorKind::InvalidData);
        assert!(
            err.to_string()
                .contains("declares multiple `Props` structs")
        );
    }

    fn mk_temp_root(prefix: &str) -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("time")
            .as_nanos();
        let root = std::env::temp_dir().join(format!(
            "pilcrow_routekit_codegen_{}_{}_{}",
            prefix,
            std::process::id(),
            nanos
        ));
        fs::create_dir_all(&root).expect("create temp root");
        root
    }

    fn write_file(path: &Path, contents: &str) {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).expect("create parent");
        }
        fs::write(path, contents).expect("write file");
    }

    fn cleanup(path: &Path) {
        if path.exists() {
            fs::remove_dir_all(path).expect("cleanup temp dir");
        }
    }

    #[test]
    fn build_generated_api_manifest_from_rs_tree() {
        let root = mk_temp_root("api_manifest");
        let src = root.join("src");

        write_file(&src.join("api/todos.rs"), "pub fn router() {}");
        write_file(&src.join("api/users/[id].rs"), "pub fn router() {}");

        let entries = build_generated_api_manifest(&src).expect("manifest should build");
        let patterns = entries
            .iter()
            .map(|e| e.pattern.as_str())
            .collect::<Vec<_>>();

        assert!(patterns.contains(&"/api/todos"));
        assert!(patterns.contains(&"/api/users/:id"));
        assert!(entries.iter().any(|e| e.symbol == "api_todos"));
        assert!(entries.iter().any(|e| e.symbol == "api_users_id"));
        assert!(entries.iter().any(|e| e.module_path == "api::users::id"));

        cleanup(&root);
    }

    #[test]
    fn render_generated_api_routes_module_contains_helpers() {
        let entries = vec![GeneratedApiRoute {
            pattern: "/api/todos".to_string(),
            module_path: "api::todos".to_string(),
            symbol: "api_todos".to_string(),
        }];

        let source = render_generated_api_routes_module(&entries);
        assert!(source.contains("pub struct GeneratedApiRoute"));
        assert!(source.contains("GENERATED_API_ROUTES"));
        assert!(source.contains("pub fn generated_api_routes()"));
        assert!(source.contains("pub fn register_generated_api_routes"));
        assert!(source.contains("GENERATED_API_ROUTES.iter().fold(router, register)"));
        assert!(source.contains("api_todos"));
        assert!(source.contains("/api/todos"));
    }

    #[test]
    fn write_generated_api_routes_module_writes_file() {
        let root = mk_temp_root("write_api_module");
        let src = root.join("src");
        let out_file = root.join("out/generated_api_routes.rs");

        write_file(&src.join("api/todos.rs"), "pub fn router() {}");
        write_file(&src.join("api/users/[id].rs"), "pub fn router() {}");

        let entries = write_generated_api_routes_module(&src, &out_file)
            .expect("should write generated file");
        assert_eq!(entries.len(), 2);
        assert!(out_file.exists());

        let generated = fs::read_to_string(&out_file).expect("read generated");
        assert!(generated.contains("/api/todos"));
        assert!(generated.contains("/api/users/:id"));
        assert!(generated.contains("api_users_id"));

        cleanup(&root);
    }
}
