use serde_json::Value;

/// The query that populates `Live` struct fields. Returned from `PilcrowLive::query()`.
pub struct LiveQuery {
    pub sql: &'static str,
    pub params: Vec<Value>,
}

/// Implemented on the `Live` struct in a route's `live.rs` file.
///
/// Routekit codegen generates the `from_row()` impl automatically.
/// Developers only implement `query()`.
pub trait PilcrowLive: Sized {
    /// Returns the SQL query and bound params used to populate all LiveProps fields.
    fn query(params: &serde_json::Map<String, Value>) -> LiveQuery;

    /// Extract field values from a query result row.
    /// Generated by routekit codegen — developer does not implement this manually.
    fn from_row(row: &std::collections::HashMap<String, Value>) -> Self;
}
