[package]
name = "sandbox-web"
version = "0.1.0"
edition = "2024"

[dependencies]
pilcrow-web = { path = "../../../crates/web" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
askama = "0.14"

[build-dependencies]
pilcrow-routekit = { path = "../../../crates/routekit" }
